/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharamacyAdmin;


import Business.EcoSystem;
import Business.Enterprise;
import Business.Patient.Patient;
import Business.Pharmacist.PharamacyAdmin;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PharmacyOrder;
import Business.WorkQueue.PlaceNewOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Soumya
 */
public class manageOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageOrderJpanel
     */
    private JPanel userProcessContainer;
    private UserAccount user;
    private EcoSystem business;
     
    Patient pat;
    DefaultTableModel dtm;
    ArrayList<Patient> array1;
    List<PharmacyOrder> orderItemList = new ArrayList<PharmacyOrder>();
    WorkRequest workrequest;
    private PharamacyAdmin pharObj;
    PlaceNewOrderWorkRequest placeWorkRequest;
    String patname;
    String pharName;
    
    String selectedPharmacy;

    
    public manageOrderJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount user,String pharmacy,String patient) {
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        //this.placeWorkRequest= placeNewOrderWorkRequest;
        this.pharName = pharmacy;
        this.patname = patient;
        this.user = user;
        initComponents();
        
        populatetable();
//        populateComboBox();
        System.out.println("Work request"+business.getWorkQueue().getWorkRequestList());
        
    }
   
    
//    public void populateComboBox(){
//        // MSS check
////         for(Enterprise res: system.findNetwork(user.getEmployee().getCity()).getEnterpriseDirectory().getEnterpriseList()){
//         for(Enterprise res: business.getEnterpriseDirectory().getEnterpriseList()){
//             
//if(res.getEnterpriseType().getValue().equals("Delivery")){
//            delManCombo.addItem(res.getName());
//         
//        }else{
//                 System.out.println("nothing");
//             }
//         }
//    }
    private void populatetable(){
        DefaultTableModel dtm = (DefaultTableModel) tblOrders.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request : business.getWorkQueue().getWorkRequestList()){
            if(request instanceof PlaceNewOrderWorkRequest){
        placeWorkRequest = (PlaceNewOrderWorkRequest) request;
        for (PharmacyOrder orderItemTotal : placeWorkRequest.getOrderTotal()){
                Object row[] = new Object[4];
                row[0] = request;
                row[1] = orderItemTotal.getCatalog().getItemName();
                row[2] = orderItemTotal.getCatalog().getItemPrice();
                row[3] = request.getStatus();

                dtm.addRow(row);
        }      
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnacceptOrder = new javax.swing.JButton();
        btndeclineOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnacceptOrder.setBackground(new java.awt.Color(52, 7, 116));
        btnacceptOrder.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnacceptOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnacceptOrder.setText("ACCEPT");
        btnacceptOrder.setPreferredSize(new java.awt.Dimension(156, 43));
        btnacceptOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacceptOrderActionPerformed(evt);
            }
        });
        add(btnacceptOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        btndeclineOrder.setBackground(new java.awt.Color(52, 7, 116));
        btndeclineOrder.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btndeclineOrder.setForeground(new java.awt.Color(255, 255, 255));
        btndeclineOrder.setText("DECLINE");
        btndeclineOrder.setPreferredSize(new java.awt.Dimension(156, 43));
        btndeclineOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeclineOrderActionPerformed(evt);
            }
        });
        add(btndeclineOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Name", "Item Name", "Price", "Status"
            }
        ));
        tblOrders.setGridColor(new java.awt.Color(255, 255, 255));
        tblOrders.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblOrders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 500, 104));

        jButton6.setBackground(new java.awt.Color(52, 7, 116));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<<");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        enterpriseLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-order-64.png"))); // NOI18N
        enterpriseLabel.setText("MANAGE ORDERS");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 310, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pharma001.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 810, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void btnacceptOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacceptOrderActionPerformed
        // TODO add your handling code here:
        
       int selectedRow = tblOrders.getSelectedRow();
               // System.out.println("Status "+orderTbl.getValueAt(selectedRow, 3)); 
       if (selectedRow <0) {
            JOptionPane.showMessageDialog(null, "You must select a row first!");
        } else {
            if (tblOrders.getValueAt(selectedRow, 3).equals("Completed")) {
                JOptionPane.showMessageDialog(null, "Order is already completed!");
            } else {
                WorkRequest request = (WorkRequest) tblOrders.getValueAt(selectedRow, 0);
                request.setStatus("Accepted");
                populatetable();
            }

        }
    
   
    }//GEN-LAST:event_btnacceptOrderActionPerformed

    private void btndeclineOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeclineOrderActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblOrders.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "You must select a row first!");
        }

        WorkRequest request = (WorkRequest) tblOrders.getValueAt(selectedRow, 0);
        if (tblOrders.getValueAt(selectedRow, 1).equals("Completed")) {
            JOptionPane.showMessageDialog(null, "Order is already processed and completed!");
        } else {
               
                request.setStatus("Declined");
                populatetable();
        }

             
        //stsTxt.setText(placeWorkRequest.getStatus());
    }//GEN-LAST:event_btndeclineOrderActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacceptOrder;
    private javax.swing.JButton btndeclineOrder;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}
