/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Labadmin;


import Business.EcoSystem;
import Business.LabAdmin.Lab;
import Business.LabAdmin.Test;
import Business.LabAdmin.TestDirectory;
import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Soumya
 */
public class AddTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddTestJPanel
     */
    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount userAccount;
     
    Lab lab;
    public AddTestJPanel(JPanel userProcessContainer, EcoSystem business, UserAccount userAccount) {
        initComponents();
        this.userAccount= userAccount;
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameTest = new javax.swing.JTextField();
        txtpriceTest = new javax.swing.JTextField();
        btnAddTest = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtsample = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtlowerRange = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtapparatus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtupperRange = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Price: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, -1));
        add(txtNameTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, 30));
        add(txtpriceTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 160, 30));

        btnAddTest.setBackground(new java.awt.Color(52, 7, 116));
        btnAddTest.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAddTest.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTest.setText("Add Test");
        btnAddTest.setPreferredSize(new java.awt.Dimension(156, 43));
        btnAddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTestActionPerformed(evt);
            }
        });
        add(btnAddTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 150, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 7, 116));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Sample Required:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, -1));
        add(txtsample, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Lower Range:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, -1));
        add(txtlowerRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 160, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 7, 116));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Apparatus:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, -1));
        add(txtapparatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 160, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 7, 116));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Upper Range:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        txtupperRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupperRangeActionPerformed(evt);
            }
        });
        add(txtupperRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 160, 30));

        jButton6.setBackground(new java.awt.Color(52, 7, 116));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<<");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-diabetes-40.png"))); // NOI18N
        enterpriseLabel.setText("ADD TEST");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 220, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab005.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 660, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTestActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        if (txtNameTest.getText().isEmpty() || txtpriceTest.getText().isEmpty() || txtsample.getText().isEmpty()||txtlowerRange.getText().isEmpty()||txtupperRange.getText().isEmpty()||txtapparatus.getText().isEmpty()||txtpriceTest.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all details of the Test");
            return;
        } else {
            if (!txtNameTest.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper Test name");
                txtNameTest.setText("");
                return;
            } else if (!txtsample.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper sample required");
                txtpriceTest.setText("");
                return;
            }    else if (!txtlowerRange.getText().matches("^-?\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Enter lower range like 4.3");
                txtlowerRange.setText("");
                return;
            } else if (!txtupperRange.getText().matches("^-?\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Enter upper range like 7.3");
                txtupperRange.setText("");
                return;
            } else if (Double.parseDouble(txtupperRange.getText())-Double.parseDouble(txtlowerRange.getText())<0) {
                JOptionPane.showMessageDialog(this, "Upper range cannot be lesser than lower range value");
                txtupperRange.setText("");
                return;
            }else if (!txtapparatus.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper apparatus required");
                txtapparatus.setText("");
                return;
            }else if (!txtpriceTest.getText().matches("^-?\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Enter price like :23.5");
                txtpriceTest.setText("");
                return;
            }else{}

            Test t = new Test(txtNameTest.getText(),txtsample.getText(),Double.parseDouble(txtlowerRange.getText()),Double.parseDouble(txtupperRange.getText()),txtapparatus.getText(), Double.parseDouble(txtpriceTest.getText()));
            // MSS check
//            if( system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName()).getTestlist()==null ||
//                system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(t.getName()) == null ) {
//                TestDirectory testList = new TestDirectory();
//                testList.addTest(t);
//                system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName()).setTestlist(testList);
//            }
//            else {
//                system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName()).getTestlist().addTest(t);
//                System.out.println("test list is here "+system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName()).getTestlist().getTestList());
//            }

            if( business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName()).getTestlist()==null ||
                business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(t.getName()) == null ) {
                TestDirectory testList = new TestDirectory();
                testList.addTest(t);
                business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName()).setTestlist(testList);
            }
            else {
                business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName()).getTestlist().addTest(t);
                System.out.println("test list is here "+business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName()).getTestlist().getTestList());
            }

        }
        JOptionPane.showMessageDialog(null, "Test added successfully");
        txtNameTest.setText("");
        txtpriceTest.setText("");
        txtsample.setText("");
        txtlowerRange.setText("");
        txtupperRange.setText("");
        txtapparatus.setText("");
        txtpriceTest.setText("");
        
    }//GEN-LAST:event_btnAddTestActionPerformed

    private void txtupperRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupperRangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtupperRangeActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTest;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtNameTest;
    private javax.swing.JTextField txtapparatus;
    private javax.swing.JTextField txtlowerRange;
    private javax.swing.JTextField txtpriceTest;
    private javax.swing.JTextField txtsample;
    private javax.swing.JTextField txtupperRange;
    // End of variables declaration//GEN-END:variables
}
