/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Labadmin;


import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BookTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Soumya
 */
public class CompleteTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompleteTestJPanel
     */
  JPanel userProcessContainer;
    UserAccount userAccount;
    EcoSystem business;
    BookTestWorkRequest request;
       
    public CompleteTestJPanel(JPanel userProcessContainer,UserAccount userAccount,EcoSystem business, BookTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount= userAccount;
        this.business=business;
        this.request= request;
        txtpatientName.setText(request.getSender().getEmployee().getName());
        txtTestId.setText(String.valueOf(request.getTestId()));
        txtDateBooked.setText(String.valueOf(request.getDateBooked()));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtpatientName = new javax.swing.JTextField();
        txtTestId = new javax.swing.JTextField();
        txtDateBooked = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btnSubmitCollected = new javax.swing.JButton();
        btnSubmitResult = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, -1));

        txtpatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientNameActionPerformed(evt);
            }
        });
        add(txtpatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 160, 30));
        add(txtTestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, 30));
        add(txtDateBooked, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setText("Test ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 75, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setText("Date booked");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 7, 116));
        jLabel6.setText("Sample collected:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 7, 116));
        jLabel7.setText("Results published:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jRadioButton1.setText("YES");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jRadioButton2.setText("NO");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jRadioButton3.setText("YES");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jRadioButton4.setText("NO");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        btnSubmitCollected.setBackground(new java.awt.Color(52, 7, 116));
        btnSubmitCollected.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSubmitCollected.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitCollected.setText("Submit");
        btnSubmitCollected.setPreferredSize(new java.awt.Dimension(156, 43));
        btnSubmitCollected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitCollectedActionPerformed(evt);
            }
        });
        add(btnSubmitCollected, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 140, 30));

        btnSubmitResult.setBackground(new java.awt.Color(52, 7, 116));
        btnSubmitResult.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSubmitResult.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitResult.setText("Submit");
        btnSubmitResult.setPreferredSize(new java.awt.Dimension(156, 43));
        btnSubmitResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitResultActionPerformed(evt);
            }
        });
        add(btnSubmitResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 140, 30));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-diabetes-40.png"))); // NOI18N
        enterpriseLabel.setText("COMPLETE TESTING");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 250, 60));

        jButton6.setBackground(new java.awt.Color(52, 7, 116));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<<");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab005.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 660, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void txtpatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientNameActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:

        this.request.setStatus("Test Sample Collected");
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        this.request.setStatus("Awaiting sample collection");
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        this.request.setStatus("Test results published ");
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        this.request.setStatus("Awaiting results ");
        jRadioButton3.setSelected(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btnSubmitCollectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitCollectedActionPerformed
        // TODO add your handling code here:
        if(request.getStatus().equals("Test Sample Collected")){
            JOptionPane.showMessageDialog(this, "Test Sample has been collected!");
        }
        else if(request.getStatus().equals("Awaiting sample collection")){
            JOptionPane.showMessageDialog(this, "Awaiting Test Sample to be collected!");
        }
        //               jRadioButton1.setSelected(false);
        //                      jRadioButton2.setSelected(false);
        
    }//GEN-LAST:event_btnSubmitCollectedActionPerformed

    private void btnSubmitResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitResultActionPerformed
        // TODO add your handling code here:
        if(request.getStatus().equals("Test results published ")){
            JOptionPane.showMessageDialog(this, "Test results have been published!");
        }
        else if(request.getStatus().equals("Awaiting results ")){
            JOptionPane.showMessageDialog(this, "Awaiting test results");
        }
        
    }//GEN-LAST:event_btnSubmitResultActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitCollected;
    private javax.swing.JButton btnSubmitResult;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField txtDateBooked;
    private javax.swing.JTextField txtTestId;
    private javax.swing.JTextField txtpatientName;
    // End of variables declaration//GEN-END:variables
}
