/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Labadmin;


import Business.EcoSystem;
import Business.LabAdmin.Lab;
import Business.LabAdmin.Test;
import Business.LabAdmin.TestDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Soumya
 */
public class ViewUpdateDeleteTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdateDeleteTestJPanel
     */
    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount userAccount;
    Lab lab;
    
    public ViewUpdateDeleteTestJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnupdateTestdets = new javax.swing.JButton();
        btndeletetestDets = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtlowerRangetestDet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtapparatustestDet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtupperRangetestDet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtnameTestDet = new javax.swing.JTextField();
        txtsampleTestDet = new javax.swing.JTextField();
        txtpricetestDet = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTestDetails = new javax.swing.JTable();
        enterpriseLabel = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnupdateTestdets.setBackground(new java.awt.Color(52, 7, 116));
        btnupdateTestdets.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnupdateTestdets.setForeground(new java.awt.Color(255, 255, 255));
        btnupdateTestdets.setText("UPDATE");
        btnupdateTestdets.setPreferredSize(new java.awt.Dimension(156, 43));
        btnupdateTestdets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateTestdetsActionPerformed(evt);
            }
        });
        add(btnupdateTestdets, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, 30));

        btndeletetestDets.setBackground(new java.awt.Color(52, 7, 116));
        btndeletetestDets.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btndeletetestDets.setForeground(new java.awt.Color(255, 255, 255));
        btndeletetestDets.setText("DELETE");
        btndeletetestDets.setPreferredSize(new java.awt.Dimension(156, 43));
        btndeletetestDets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletetestDetsActionPerformed(evt);
            }
        });
        add(btndeletetestDets, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 130, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setText("Lower Range:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));
        add(txtlowerRangetestDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 140, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 7, 116));
        jLabel6.setText("Apparatus:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));
        add(txtapparatustestDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 140, 30));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 7, 116));
        jLabel7.setText("Upper Range:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        txtupperRangetestDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupperRangetestDetActionPerformed(evt);
            }
        });
        add(txtupperRangetestDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 140, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setText("Price: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 7, 116));
        jLabel4.setText("Sample Required:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));
        add(TxtnameTestDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 140, 30));
        add(txtsampleTestDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 140, 30));
        add(txtpricetestDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 140, 30));

        tblTestDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Sample Required", "Lower Range", "Upper Range", "Apparatus", "Price"
            }
        ));
        tblTestDetails.setGridColor(new java.awt.Color(255, 255, 255));
        tblTestDetails.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblTestDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTestDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTestDetails);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 479, 122));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-test-48.png"))); // NOI18N
        enterpriseLabel.setText("TEST DETAILS");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 230, 50));

        jButton6.setBackground(new java.awt.Color(52, 7, 116));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<<");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab005.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 660, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateTestdetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateTestdetsActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblTestDetails.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        } else {
            if (!TxtnameTestDet.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper Test name");
                TxtnameTestDet.setText("");
                return;
            } else if (!txtsampleTestDet.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper sample required");
                txtpricetestDet.setText("");
                return;
            }    else if (!txtlowerRangetestDet.getText().matches("^-?\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Enter lower range like 4.3");
                txtlowerRangetestDet.setText("");
                return;
            } else if (!txtupperRangetestDet.getText().matches("^-?\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Enter upper range like 7.3");
                txtupperRangetestDet.setText("");
                return;
            } else if (Double.parseDouble(txtupperRangetestDet.getText())-Double.parseDouble(txtlowerRangetestDet.getText())<0) {
                JOptionPane.showMessageDialog(this, "Upper range cannot be lesser than lower range value");
                txtupperRangetestDet.setText("");
                return;
            }else if (!txtapparatustestDet.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper apparatus required");
                txtapparatustestDet.setText("");
                return;
            }else if (!txtpricetestDet.getText().matches("^-?\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Enter price like :23.5");
                txtpricetestDet.setText("");
                return;
            }else{}
            //            updateJPanel.setVisible(true);
            System.out.println("I am here");

            Test t = (Test) tblTestDetails.getValueAt(selectedRow, 0);
            System.out.println("item : " + t.getName());
            t.setName(TxtnameTestDet.getText());
            t.setSample(txtsampleTestDet.getText());
            t.setLowerRange(Double.parseDouble(txtlowerRangetestDet.getText()));
            t.setUpperRange(Double.parseDouble(txtupperRangetestDet.getText()));
            t.setApparatus(txtapparatustestDet.getText());
            t.setPrice(Double.parseDouble(txtpricetestDet.getText()));
            populateTable();
            TxtnameTestDet.setText("");
            txtpricetestDet.setText("");
            txtsampleTestDet.setText("");
            txtlowerRangetestDet.setText("");
            txtupperRangetestDet.setText("");
            txtapparatustestDet.setText("");
            txtpricetestDet.setText("");
        }
        
    }//GEN-LAST:event_btnupdateTestdetsActionPerformed

    private void btndeletetestDetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletetestDetsActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblTestDetails.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");

        } else {
            Test t = (Test) tblTestDetails.getValueAt(selectedRow, 0);
            // MSS check
//            Lab lab= system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName());
            Lab lab= business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName());
            
            lab.deleteTest(t);
            JOptionPane.showMessageDialog(null, "Test " + TxtnameTestDet.getText() + " deleted");
            populateTable();
            TxtnameTestDet.setText("");
            txtpricetestDet.setText("");
            txtsampleTestDet.setText("");
            txtlowerRangetestDet.setText("");
            txtupperRangetestDet.setText("");
            txtapparatustestDet.setText("");
            txtpricetestDet.setText("");

        }
        
    }//GEN-LAST:event_btndeletetestDetsActionPerformed

    private void txtupperRangetestDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupperRangetestDetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtupperRangetestDetActionPerformed

    private void tblTestDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTestDetailsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblTestDetails.getModel();

        String name = dtm.getValueAt(tblTestDetails.getSelectedRow(), 0).toString();
        String sample = dtm.getValueAt(tblTestDetails.getSelectedRow(), 1).toString();
        Double lowerRange = Double.parseDouble(dtm.getValueAt(tblTestDetails.getSelectedRow(), 2).toString());
        Double upperRange = Double.parseDouble(dtm.getValueAt(tblTestDetails.getSelectedRow(), 3).toString());
        String apparatus = dtm.getValueAt(tblTestDetails.getSelectedRow(),4).toString();
        Double price = Double.parseDouble(dtm.getValueAt(tblTestDetails.getSelectedRow(), 5).toString());

        TxtnameTestDet.setText(name);
        txtsampleTestDet.setText(sample);
        txtlowerRangetestDet.setText(String.valueOf(lowerRange));
        txtupperRangetestDet.setText(String.valueOf(upperRange));
        txtapparatustestDet.setText(apparatus);
        txtpricetestDet.setText(String.valueOf(price));

    }//GEN-LAST:event_tblTestDetailsMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtnameTestDet;
    private javax.swing.JButton btndeletetestDets;
    private javax.swing.JButton btnupdateTestdets;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTestDetails;
    private javax.swing.JTextField txtapparatustestDet;
    private javax.swing.JTextField txtlowerRangetestDet;
    private javax.swing.JTextField txtpricetestDet;
    private javax.swing.JTextField txtsampleTestDet;
    private javax.swing.JTextField txtupperRangetestDet;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblTestDetails.getModel();
        model.setRowCount(0);
        // MSS check
//       Lab lab= system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName());
        Lab lab= business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getLabDirectory().findLab(userAccount.getEmployee().getName());


            for(Test t1: lab.getTestlist().getTestList()){
            Object[] row = new Object[6];
            row[0] = t1;
            row[1] = t1.getSample();
            row[2] = t1.getLowerRange();
            row[3] = t1.getUpperRange();
            row[4] = t1.getApparatus();
            row[5] = t1.getPrice();
            model.addRow(row);
               }
        }
    
}

