/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.Doctor.Doctor;
import Business.Doctor.DoctorDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization;
import Business.Role.DoctorRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Soumya
 */
public class AddDoctorJpanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDoctorJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount user;
    
    public AddDoctorJpanel(JPanel userProcessContainer,EcoSystem business,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDocPwd = new javax.swing.JTextField();
        btnBackAD = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDocEmail = new javax.swing.JTextField();
        txtDocNum = new javax.swing.JTextField();
        btnAddDoc = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDocSpl = new javax.swing.JTextField();
        txtDocUname = new javax.swing.JTextField();
        txtDocName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtDocPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 170, 30));

        btnBackAD.setBackground(new java.awt.Color(52, 7, 116));
        btnBackAD.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBackAD.setForeground(new java.awt.Color(255, 255, 255));
        btnBackAD.setText("<<");
        btnBackAD.setPreferredSize(new java.awt.Dimension(80, 30));
        btnBackAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackADActionPerformed(evt);
            }
        });
        add(btnBackAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 7, 116));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-doctor-40.png"))); // NOI18N
        jLabel6.setText("ADD DOCTOR");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 330, 60));

        txtDocEmail.setPreferredSize(new java.awt.Dimension(15, 30));
        txtDocEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocEmailActionPerformed(evt);
            }
        });
        add(txtDocEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 170, 30));

        txtDocNum.setPreferredSize(new java.awt.Dimension(15, 30));
        add(txtDocNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 170, 30));

        btnAddDoc.setBackground(new java.awt.Color(52, 7, 116));
        btnAddDoc.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDoc.setText("Add Doctor");
        btnAddDoc.setPreferredSize(new java.awt.Dimension(156, 43));
        btnAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocActionPerformed(evt);
            }
        });
        add(btnAddDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        jLabel10.setBackground(new java.awt.Color(52, 7, 116));
        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(52, 7, 116));
        jLabel10.setText("Email");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        jLabel11.setBackground(new java.awt.Color(52, 7, 116));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(52, 7, 116));
        jLabel11.setText("Phone");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        txtDocSpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocSplActionPerformed(evt);
            }
        });
        add(txtDocSpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 170, 30));
        add(txtDocUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 170, 30));
        add(txtDocName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 170, 30));

        jLabel5.setBackground(new java.awt.Color(52, 7, 116));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        jLabel4.setBackground(new java.awt.Color(52, 7, 116));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 7, 116));
        jLabel4.setText("Username");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        jLabel3.setBackground(new java.awt.Color(52, 7, 116));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setText("Specialization");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jLabel2.setBackground(new java.awt.Color(52, 7, 116));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setText("Doctor Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/docImg2.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 910, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackADActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_btnBackADActionPerformed

    private void btnAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocActionPerformed
        // TODO add your handling code here:
        if (txtDocUname.getText().isEmpty() || txtDocPwd.getText().isEmpty() || txtDocName.getText().isEmpty() || txtDocSpl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter all mandatory fields");
        } else {

            if (!txtDocName.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper name! Name should be string!");
                txtDocName.setText("");
                return;
            }
            else if(!txtDocSpl.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper specialization name");
                txtDocSpl.setText("");
                return;
            }
            else if(!txtDocEmail.getText().matches("^(.+)@(.+)$")){
                JOptionPane.showMessageDialog(this, "Enter proper Email in the format of abc@gmail.com");
                txtDocEmail.setText("");
                return;
            }
            else if(!txtDocNum.getText().matches("^\\d{10}$")){
                JOptionPane.showMessageDialog(this, "Enter a 10 digit phone number");
                txtDocNum.setText("");
                return;
            }
            if (strongUsername() == false) {
                txtDocUname.setText("");
                JOptionPane.showMessageDialog(null, "Username should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
                return;
            } else {
                String userName = txtDocUname.getText();
            }
            if (strongPassword() == false) {
                txtDocPwd.setText("");
                JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
                return;
            } else {
            }
            String hospname = user.getEmployee().getName();
            System.out.println("HospitalName"+hospname);
            String name = txtDocName.getText();
            String spcl = txtDocSpl.getText();
            String username = txtDocUname.getText();
            String pass = txtDocPwd.getText();

            // MSS check - setting loc for doctor
//            String city = "Boston";
            Employee emp = business.getEmployeeDirectory().createEmployee(name);
//            emp.setCity(city);
            UserAccount account = business.getUserAccountDirectory().createUserAccount(username, pass, emp, new DoctorRole());
            System.out.println("oooo"+business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().findOrganization(name));
            System.out.println("ppp"+business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getOrganizationList());
            if(business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getOrganizationList()==null ||business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().findOrganization(name)==null){
                business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().createOrganization(name, Organization.Type.Doctor,spcl);
                JOptionPane.showMessageDialog(this," Doctor created");
                txtDocName.setText("");
                txtDocSpl.setText("");
                txtDocEmail.setText("");
                txtDocNum.setText("");
                txtDocUname.setText("");
                txtDocPwd.setText("");
            }else{
                System.out.println("Already exists");
                JOptionPane.showMessageDialog(this," Doctor already exists");
                // System.out.println(system.findNetwork(city).getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getOrganizationList().size());
                //            DoctorDirectory doctordirectory =new DoctorDirectory();
                //            Doctor doctor = new Doctor();
                //            ArrayList<Doctor> doclist = new ArrayList<>();
                //            doctor.setName(name);
                //            doctor.setSpecialization(spcl);
                //            doclist.add(doctor);
                //            doctordirectory.setDoctorList(doclist);
                //            system.getHospitalDirectory().findHospital(hospname).setDoctorDirectory(doctordirectory);
            }
        }
    }//GEN-LAST:event_btnAddDocActionPerformed

    private void txtDocSplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocSplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocSplActionPerformed

    private void txtDocEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocEmailActionPerformed

    
        private boolean strongUsername() {
        Pattern pat = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m = pat.matcher(txtDocUname.getText());
        boolean boo = m.matches();
        return boo;
    }

    private boolean strongPassword() {
        Pattern pat1;
        pat1 = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m1 = pat1.matcher(txtDocPwd.getText());
        boolean bat1 = m1.matches();
        return bat1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDoc;
    private javax.swing.JButton btnBackAD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDocEmail;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtDocNum;
    private javax.swing.JTextField txtDocPwd;
    private javax.swing.JTextField txtDocSpl;
    private javax.swing.JTextField txtDocUname;
    // End of variables declaration//GEN-END:variables
}
