/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.HospitalAdmin.Hospital;
import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Soumya
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount user;
    private Hospital resObj;
    private String hosname;
       
    public DoctorJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.user = user;
        hosname = user.getEmployee().getName();
        viewTable();
    }
    
    
      
    public void viewTable(){
     
        DefaultTableModel dtm = (DefaultTableModel) doctorDetailsMngDoc.getModel();
        dtm.setRowCount(0);
        
         //System.out.println("Res len "+ system.getDoctorDirectory().getDoctorList());
//       String loc = user.getEmployee().getCity();

         
        if(business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getOrganizationList()!=null &&business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getDoctorDirectory()!=null){
        for(Doctor org : business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getDoctorDirectory().getDoctorList()) {
           //System.out.println(org.getEnterpriseType1().getClass()+" "+ org.getEnterpriseType1().getValue());
              
            Object row[] = new Object[3];
            row[0] = org;
            row[1] = org.getSpecialization();
            dtm.addRow(row);
        
        }
        System.out.println("hooos "+hosname);
   }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doctorDetailsMngDoc = new javax.swing.JTable();
        btncreateNewDoctorMng = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        btnMngDocBack = new javax.swing.JButton();
        btnDocRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorDetailsMngDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Doctor name", "Doctor Specialization"
            }
        ));
        doctorDetailsMngDoc.setGridColor(new java.awt.Color(255, 255, 255));
        doctorDetailsMngDoc.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(doctorDetailsMngDoc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 510, 110));

        btncreateNewDoctorMng.setBackground(new java.awt.Color(52, 7, 116));
        btncreateNewDoctorMng.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btncreateNewDoctorMng.setForeground(new java.awt.Color(255, 255, 255));
        btncreateNewDoctorMng.setText("Create New Doctor");
        btncreateNewDoctorMng.setPreferredSize(new java.awt.Dimension(156, 43));
        btncreateNewDoctorMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateNewDoctorMngActionPerformed(evt);
            }
        });
        add(btncreateNewDoctorMng, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 210, 40));

        enterpriseLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-doctor-40.png"))); // NOI18N
        enterpriseLabel.setText("MANAGE DOCTORS");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 360, 50));

        btnMngDocBack.setBackground(new java.awt.Color(52, 7, 116));
        btnMngDocBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnMngDocBack.setForeground(new java.awt.Color(255, 255, 255));
        btnMngDocBack.setText("<<");
        btnMngDocBack.setPreferredSize(new java.awt.Dimension(80, 30));
        btnMngDocBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngDocBackActionPerformed(evt);
            }
        });
        add(btnMngDocBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        btnDocRefresh.setBackground(new java.awt.Color(52, 7, 116));
        btnDocRefresh.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnDocRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnDocRefresh.setText("Refresh");
        btnDocRefresh.setPreferredSize(new java.awt.Dimension(156, 43));
        btnDocRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocRefreshActionPerformed(evt);
            }
        });
        add(btnDocRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 110, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/docImg2.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1110, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateNewDoctorMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateNewDoctorMngActionPerformed
        // TODO add your handling code here:

        AddDoctorJpanel createDoctorJPanel = new AddDoctorJpanel(userProcessContainer, business,user);
        userProcessContainer.add("CreateDoctor", createDoctorJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btncreateNewDoctorMngActionPerformed

    private void btnMngDocBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngDocBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_btnMngDocBackActionPerformed

    private void btnDocRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocRefreshActionPerformed
        // TODO add your handling code here:
        viewTable();
    }//GEN-LAST:event_btnDocRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocRefresh;
    private javax.swing.JButton btnMngDocBack;
    private javax.swing.JButton btncreateNewDoctorMng;
    private javax.swing.JTable doctorDetailsMngDoc;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
