/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Administrator;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise;
import Business.HospitalAdmin.Hospital;
import Business.Organization;
import Business.Role.DoctorRole;
import Business.Role.HospitalAdminRole;
import Business.Role.LabAdminRole;
import Business.Role.PharamacyAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Smithi
 */
public class AddPharmacy extends javax.swing.JPanel {

    /**
     * Creates new form AddPharmacy
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    UserAccount user;
    public AddPharmacy(JPanel userProcessContainer,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPharmaName = new javax.swing.JTextField();
        txtPharmaAddr = new javax.swing.JTextField();
        txtPharmaUName = new javax.swing.JTextField();
        txtPharmaPwd = new javax.swing.JTextField();
        addPharma = new javax.swing.JButton();
        btnBackPharma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboLocPharma = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtPharmaEmail = new javax.swing.JTextField();
        txtPharmaNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Pharmacy Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 120, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 7, 116));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Username:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 90, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Password:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 90, -1));

        txtPharmaName.setPreferredSize(new java.awt.Dimension(164, 30));
        add(txtPharmaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        txtPharmaAddr.setPreferredSize(new java.awt.Dimension(164, 30));
        add(txtPharmaAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        txtPharmaUName.setPreferredSize(new java.awt.Dimension(164, 30));
        add(txtPharmaUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        txtPharmaPwd.setPreferredSize(new java.awt.Dimension(164, 30));
        add(txtPharmaPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        addPharma.setBackground(new java.awt.Color(52, 7, 116));
        addPharma.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        addPharma.setForeground(new java.awt.Color(255, 255, 255));
        addPharma.setText("Add Pharmacy");
        addPharma.setPreferredSize(new java.awt.Dimension(156, 43));
        addPharma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPharmaActionPerformed(evt);
            }
        });
        add(addPharma, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 200, -1));

        btnBackPharma.setBackground(new java.awt.Color(52, 7, 116));
        btnBackPharma.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        btnBackPharma.setForeground(new java.awt.Color(255, 255, 255));
        btnBackPharma.setText("<<");
        btnBackPharma.setPreferredSize(new java.awt.Dimension(80, 30));
        btnBackPharma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackPharmaActionPerformed(evt);
            }
        });
        add(btnBackPharma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 7, 116));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-pharmacy-shop-64.png"))); // NOI18N
        jLabel1.setText("ADD PHARMACY");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 450, 60));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 7, 116));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("City Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 90, -1));

        comboLocPharma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brigham", "Cambridge", "Brookline", "Longwood", "Fenway" }));
        comboLocPharma.setPreferredSize(new java.awt.Dimension(140, 30));
        comboLocPharma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocPharmaActionPerformed(evt);
            }
        });
        add(comboLocPharma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 160, -1));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtPharmaEmail.setPreferredSize(new java.awt.Dimension(15, 30));
        add(txtPharmaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 164, -1));

        txtPharmaNum.setPreferredSize(new java.awt.Dimension(15, 30));
        add(txtPharmaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 164, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(52, 7, 116));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Email:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 70, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(52, 7, 116));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Phone:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 80, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phar123.jpg"))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 360, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void addPharmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPharmaActionPerformed
        // TODO add your handling code here:
        if (txtPharmaUName.getText().isEmpty() || txtPharmaPwd.getText().isEmpty() || txtPharmaName.getText().isEmpty() || txtPharmaAddr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter all mandatory fields");
        } else {
            if (!txtPharmaName.getText().matches("[a-zA-Z0-9]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper name");
                txtPharmaName.setText("");
                return;
            }
            else if(!txtPharmaAddr.getText().matches("\\d+\\s+([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+)")) {
                JOptionPane.showMessageDialog(this, "Enter proper Address in the format 123 abcd");
                txtPharmaAddr.setText("");
                return;
            }
            else if(!txtPharmaEmail.getText().matches("^(.+)@(.+)$")){
                JOptionPane.showMessageDialog(this, "Enter proper Email in the format of abc@gmail.com");
                txtPharmaEmail.setText("");
                return;
            }
            else if(!txtPharmaNum.getText().matches("^\\d{10}$")){
                JOptionPane.showMessageDialog(this, "Enter a 10 digit phone number");
                txtPharmaNum.setText("");
                return;
            }

            else if (strongUsername() == false) {
                txtPharmaUName.setText("");
                JOptionPane.showMessageDialog(null, "should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
                return;
            }
            else if (strongPassword() == false) {
                txtPharmaPwd.setText("");
                JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
                return;
            } else {
            }
            // name = keyboard.nextLine();

            String name = txtPharmaName.getText();
            String add = txtPharmaAddr.getText();
            String username = txtPharmaUName.getText();
            String pass = txtPharmaPwd.getText();
            Object selectedItem = comboLocPharma.getSelectedItem();
            //String name;

            String loc = selectedItem.toString();
            //String city = "Boston";
            Employee emp = business.getEmployeeDirectory().createEmployee(name);
            emp.setLocation(loc);

            UserAccount account = business.getUserAccountDirectory().createUserAccount(username, pass, emp, new PharamacyAdminRole());

            if (business.getEnterpriseDirectory().findEnterprise(name) == null) {
                business.getEnterpriseDirectory().createAndAddEnterprise(name, Enterprise.EnterpriseType.Pharmacy );
                business.getEnterpriseDirectory().findEnterprise(name).getOrganizationDirectory().createOrganization(name, Organization.Type.PharamacyAdmin, "Test");
                JOptionPane.showMessageDialog(this," Pharmacy created");
                //System.out.println(name);
                //System.out.println("adding p" +system.findNetwork(city).getEnterpriseDirectory().findEnterprise(name).getOrganizationDirectory().getPharmacyAdminDirectory().getPharmacyList());
                txtPharmaName.setText("");
                txtPharmaAddr.setText("");
                txtPharmaEmail.setText("");
                txtPharmaNum.setText("");
                txtPharmaUName.setText("");
                txtPharmaPwd.setText("");
            }
            else{
                //JOptionPane.showMessageDialog(this,"already there");
                JOptionPane.showMessageDialog(this," Pharmacy already exist");
                // System.out.println("already there");
            }
        }
    }//GEN-LAST:event_addPharmaActionPerformed

    private void btnBackPharmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackPharmaActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_btnBackPharmaActionPerformed

    private void comboLocPharmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocPharmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLocPharmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPharma;
    private javax.swing.JButton btnBackPharma;
    private javax.swing.JComboBox<String> comboLocPharma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtPharmaAddr;
    private javax.swing.JTextField txtPharmaEmail;
    private javax.swing.JTextField txtPharmaName;
    private javax.swing.JTextField txtPharmaNum;
    private javax.swing.JTextField txtPharmaPwd;
    private javax.swing.JTextField txtPharmaUName;
    // End of variables declaration//GEN-END:variables

private boolean strongUsername() {
        Pattern pat = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m = pat.matcher(txtPharmaUName.getText());
        boolean boo = m.matches();
        return boo;
    }

    private boolean strongPassword() {
        Pattern pat1;
        pat1 = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m1 = pat1.matcher(txtPharmaPwd.getText());
        boolean bat1 = m1.matches();
        return bat1;
    }
}