/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Doctor.DoctorJPanel;


/**
 *
 * @author Malini
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem business;
    private UserAccount user;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business=business;
        this.user = user;
        //valueLabel.setText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHAPatients = new javax.swing.JButton();
        btnHADocs = new javax.swing.JButton();
        btnHAOrderInven = new javax.swing.JButton();
        btnHAOrderMed = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHAPatients.setBackground(new java.awt.Color(52, 7, 116));
        btnHAPatients.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnHAPatients.setForeground(new java.awt.Color(255, 255, 255));
        btnHAPatients.setText("Patient");
        btnHAPatients.setPreferredSize(new java.awt.Dimension(156, 43));
        btnHAPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPatientsActionPerformed(evt);
            }
        });
        add(btnHAPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 170, -1));

        btnHADocs.setBackground(new java.awt.Color(52, 7, 116));
        btnHADocs.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnHADocs.setForeground(new java.awt.Color(255, 255, 255));
        btnHADocs.setText("Doctor");
        btnHADocs.setPreferredSize(new java.awt.Dimension(156, 43));
        btnHADocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHADocsActionPerformed(evt);
            }
        });
        add(btnHADocs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, -1));

        btnHAOrderInven.setBackground(new java.awt.Color(52, 7, 116));
        btnHAOrderInven.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnHAOrderInven.setForeground(new java.awt.Color(255, 255, 255));
        btnHAOrderInven.setText("Order Inventory");
        btnHAOrderInven.setPreferredSize(new java.awt.Dimension(156, 43));
        btnHAOrderInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAOrderInvenActionPerformed(evt);
            }
        });
        add(btnHAOrderInven, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, -1));

        btnHAOrderMed.setBackground(new java.awt.Color(52, 7, 116));
        btnHAOrderMed.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnHAOrderMed.setForeground(new java.awt.Color(255, 255, 255));
        btnHAOrderMed.setText("Order Medicine");
        btnHAOrderMed.setPreferredSize(new java.awt.Dimension(156, 43));
        btnHAOrderMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAOrderMedActionPerformed(evt);
            }
        });
        add(btnHAOrderMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 170, -1));

        enterpriseLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-admin-48.png"))); // NOI18N
        enterpriseLabel.setText("HOSPITAL ADMIN DASHBOARD");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 420, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Patient567.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 730, 1130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHAPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPatientsActionPerformed
        // TODO add your handling code here:
        AddPatientJPanel AddPatentJPanel = new AddPatientJPanel(userProcessContainer, business,user);
        userProcessContainer.add("CreatePatient", AddPatentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnHAPatientsActionPerformed

    private void btnHADocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHADocsActionPerformed
       
        DoctorJPanel doctorJPanel = new DoctorJPanel(userProcessContainer,business,user);
        userProcessContainer.add("Doctors", doctorJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHADocsActionPerformed

    private void btnHAOrderInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAOrderInvenActionPerformed
        // TODO add your handling code here:

        ManageInventoryJPanel manageInventory = new ManageInventoryJPanel(userProcessContainer, user, business);
        userProcessContainer.add("ManageInventory", manageInventory);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnHAOrderInvenActionPerformed

    private void btnHAOrderMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAOrderMedActionPerformed
        // TODO add your handling code here:
        orderMedHospitalJPanel hosorderJPanel = new orderMedHospitalJPanel(userProcessContainer, user, business, user.getEmployee().getName());
        userProcessContainer.add("Hospital Order", hosorderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHAOrderMedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHADocs;
    private javax.swing.JButton btnHAOrderInven;
    private javax.swing.JButton btnHAOrderMed;
    private javax.swing.JButton btnHAPatients;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
