/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharamacyAdmin;


import Business.EcoSystem;
import Business.Enterprise;
import Business.Organization;
import Business.Patient.Patient;
import Business.Pharmacist.PharamacyAdmin;
import Business.PharmacyCatalog.PharmacyCatalog;
import Business.PharmacyCatalog.PharmacyCatalogDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PharmacyOrder;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Soumya
 */
public class addMedicineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form addMedicineJpanel
     */
    private JPanel userProcessContainer;
    private UserAccount user;
    private EcoSystem business;
      
    private String pharmName;
    ArrayList<Patient> array1;
    List<PharmacyOrder> orderItemList = new ArrayList<PharmacyOrder>();
    WorkRequest workrequest;
    PharmacyCatalog catalog;
    Patient pat;
    PharamacyAdmin pharm;
    String pharname;
    
    
    public addMedicineJPanel(JPanel userProcessContainer,EcoSystem business,String pharname,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.pharname = pharname;
        this.user = user;
        System.out.println("user"+pharname);
        viewTable();
        //this.pharm = pharm;
    }
    
    public void viewTable(){
        DefaultTableModel dtm = (DefaultTableModel) tbladdMed.getModel();
        dtm.setRowCount(0);
        
        
        // Restaurant ro1 = system.getRestaurantDirectory().findRestaurant(resName);
//        PharamacyAdmin phar = system.findNetwork(user.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory().findPharmacy(pharname);
//            System.out.println("Username"+system.findNetwork(user.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory().findPharmacy(pharname));
//            if(phar.getPharDir()!=null){
//            for(PharmacyCatalog m : phar.getPharDir().getCatalog()  ) {
//               System.out.println(system.findNetwork(user.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory().getPharmacyList().size());
//                Object row[] = new Object[3];
//                row[0] = m.getItemName();
//                row[1] = m.getItemPrice();
//
//                dtm.addRow(row);
//            }
//                    }

        // MSS check
        PharamacyAdmin phar = business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory().findPharmacy(pharname);
            System.out.println("Username"+ business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory().findPharmacy(pharname));
            if(phar.getPharDir()!=null){
            for(PharmacyCatalog m : phar.getPharDir().getCatalog()  ) {
               System.out.println( business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory().getPharmacyList().size());
                Object row[] = new Object[3];
                row[0] = m.getItemName();
                row[1] = m.getItemPrice();

                dtm.addRow(row);
            }
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbladdMed = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmedName = new javax.swing.JTextField();
        txtmedPrice = new javax.swing.JTextField();
        btnaddMed = new javax.swing.JButton();
        btnrefreshMedTbl = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbladdMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Medicine", "Price"
            }
        ));
        tbladdMed.setGridColor(new java.awt.Color(255, 255, 255));
        tbladdMed.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tbladdMed);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 350, 103));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 7, 116));
        jLabel1.setText("Medicine Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setText("Medicine Price:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        txtmedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedNameActionPerformed(evt);
            }
        });
        add(txtmedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 190, 30));
        add(txtmedPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 190, 30));

        btnaddMed.setBackground(new java.awt.Color(52, 7, 116));
        btnaddMed.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnaddMed.setForeground(new java.awt.Color(255, 255, 255));
        btnaddMed.setText("ADD");
        btnaddMed.setPreferredSize(new java.awt.Dimension(156, 43));
        btnaddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddMedActionPerformed(evt);
            }
        });
        add(btnaddMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 100, 30));

        btnrefreshMedTbl.setBackground(new java.awt.Color(52, 7, 116));
        btnrefreshMedTbl.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnrefreshMedTbl.setForeground(new java.awt.Color(255, 255, 255));
        btnrefreshMedTbl.setText("Refresh");
        btnrefreshMedTbl.setPreferredSize(new java.awt.Dimension(156, 43));
        btnrefreshMedTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshMedTblActionPerformed(evt);
            }
        });
        add(btnrefreshMedTbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 120, 30));

        jButton6.setBackground(new java.awt.Color(52, 7, 116));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<<");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-medicine-48.png"))); // NOI18N
        enterpriseLabel.setText("Add Medicine");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 300, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pharma001.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 970, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void txtmedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmedNameActionPerformed

    private void btnaddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddMedActionPerformed
        // TODO add your handling code here:
 if (txtmedName.getText().isEmpty() || txtmedPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter all mandatory fields");
        } else {
            if (!txtmedName.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper medicine name");
                txtmedName.setText("");
                return;
            }
            else if(!txtmedPrice.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Medice price should be in integers");
                txtmedPrice.setText("");
                return;
            }

//            else if (strongUsername() == false) {
//                dUname.setText("");
//                JOptionPane.showMessageDialog(null, "Username should be in the format of aa_aa@aa.aa");
//                return;
//            } 
//            else if (strongPassword() == false) {
//                dPass.setText("");
//                JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
//                return;
//            } 
            else {
            }
        String menuIt = txtmedName.getText();
        Double ip = Double.valueOf(txtmedPrice.getText());
        PharmacyCatalog m = new PharmacyCatalog();
//        System.out.println("Test "+user.getEmployee().getCity());
//        System.out.println(pharname);
//       System.out.println(system.findNetwork(user.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()));     
//       //System.out.println();
//       System.out.println(system.findNetwork(user.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(pharname).getOrganizationDirectory().getPharmacyAdminDirectory().getPharmacyList());
//       System.out.println("trying "+system.findNetwork(user.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise("phar").getOrganizationDirectory().getPharmacyAdminDirectory().findPharmacy("phar"));
        PharamacyAdmin pha = business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory().findPharmacy(pharname);
        
        m.setItemName(menuIt);
        m.setItemPrice(ip);
//                System.out.println("Directory +++++"+pha.getPharDir());
            
            if( pha.getPharDir()!= null){
            //PharmacyDirectory d = new PharmacyCatalogDirectory();
            PharmacyCatalogDirectory pd = pha.getPharDir();
            ArrayList<PharmacyCatalog> am  = pha.getPharDir().getCatalog();
            am.add(m);
            pd.setCatalog(am);
            pha.setPharDir(pd);
//            system.getPharmacyDirectory().setCatalog(am);
//            System.out.println(system);
//            system.setPharmacyDirectory(system.getPharmacyDirectory());
//            System.out.println(m.getItemName());
        }
            else{
            PharmacyCatalogDirectory d = new PharmacyCatalogDirectory();
            ArrayList<PharmacyCatalog> am  = new ArrayList<>();
            am.add(m);
            d.setCatalog(am);
            pha.setPharDir(d);
//            System.out.println(system);
//            system.setPharmacyDirectory(d);
//            System.out.println(m.getItemName());
            }
            viewTable();
            }
            JOptionPane.showMessageDialog(null, "Medicine Added");
               
             txtmedName.setText("");
             txtmedPrice.setText("");
    
 
    }//GEN-LAST:event_btnaddMedActionPerformed

    private void btnrefreshMedTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshMedTblActionPerformed
        // TODO add your handling code here:
        viewTable();
    }//GEN-LAST:event_btnrefreshMedTblActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddMed;
    private javax.swing.JButton btnrefreshMedTbl;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbladdMed;
    private javax.swing.JTextField txtmedName;
    private javax.swing.JTextField txtmedPrice;
    // End of variables declaration//GEN-END:variables
}
