/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharamacyAdmin;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Pharmacist.PharamacyAdmin;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PlaceNewOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Soumya
 */
public class PharamacyAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharamacyAdminJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount user;
    private EcoSystem business;
    String pharName;
    String patName;
    PlaceNewOrderWorkRequest newOrder;
    WorkRequest wq;
    Employee emp;
    PharamacyAdmin phar;
    
public PharamacyAdminJPanel(JPanel userProcessContainer, UserAccount ua,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.user = ua;
//        System.out.println("City "+user.getEmployee().getCity());
//        System.out.println("User"+user.getEmployee().getName());
        pharName = user.getEmployee().getName();
       // MSS check
//        System.out.println(system.findNetwork(user.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory());
                System.out.println(business.getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory());

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngEmployee = new javax.swing.JButton();
        btnMngOrders = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMngEmployee.setBackground(new java.awt.Color(52, 7, 115));
        btnMngEmployee.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMngEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnMngEmployee.setText("Add new medications");
        btnMngEmployee.setPreferredSize(new java.awt.Dimension(156, 43));
        btnMngEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngEmployeeActionPerformed(evt);
            }
        });
        add(btnMngEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, -1));

        btnMngOrders.setBackground(new java.awt.Color(52, 7, 115));
        btnMngOrders.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMngOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnMngOrders.setText("Manage Orders");
        btnMngOrders.setPreferredSize(new java.awt.Dimension(156, 43));
        btnMngOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngOrdersActionPerformed(evt);
            }
        });
        add(btnMngOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-admin-48.png"))); // NOI18N
        enterpriseLabel1.setText("PHARMACY ADMIN");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 250, 80));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pharma001.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 660, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngEmployeeActionPerformed
        
        addMedicineJPanel addMed = new addMedicineJPanel(userProcessContainer, business,pharName,user);
        userProcessContainer.add("CreateHospital", addMed);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnMngEmployeeActionPerformed

    private void btnMngOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngOrdersActionPerformed
        
        manageOrderJPanel orderMan = new manageOrderJPanel(userProcessContainer, business, user,pharName, patName);
        userProcessContainer.add("CreateHospital", orderMan);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnMngOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngEmployee;
    private javax.swing.JButton btnMngOrders;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
