/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplierAdmin;


import userinterface.Labadmin.*;
import Business.EcoSystem;
import Business.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderInventoryWorkRequest;
import Business.WorkQueue.PlaceNewOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Malini
 */


public class CompleteOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GenerateTestReport
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    EcoSystem business;
    OrderInventoryWorkRequest request;
    String selectedPharmacy;
    
    
public CompleteOrderJPanel(JPanel userProcessContainer,UserAccount userAccount,EcoSystem business, OrderInventoryWorkRequest request) {
        initComponents();
        this.userAccount= userAccount;
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.request= request;
        txtInventoryItems.setText(request.getInventoryList().toString());
        txtDateOrderedInventory.setText(String.valueOf(request.getRequestDate()));
        populatetable();
//        populateComboBox();
           
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtInventoryItems = new javax.swing.JTextField();
        txtDateOrderedInventory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventoryOrder = new javax.swing.JTable();
        btnacceptOrderInv = new javax.swing.JButton();
        btndeclineOrderInv = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        btnBackCO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Items:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 110, -1));

        txtInventoryItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInventoryItemsActionPerformed(evt);
            }
        });
        add(txtInventoryItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 150, 30));
        add(txtDateOrderedInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 150, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Date Ordered:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 130, -1));

        tblInventoryOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Items", "Date ordered", "status"
            }
        ));
        tblInventoryOrder.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblInventoryOrder);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 480, 111));

        btnacceptOrderInv.setBackground(new java.awt.Color(52, 7, 116));
        btnacceptOrderInv.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnacceptOrderInv.setForeground(new java.awt.Color(255, 255, 255));
        btnacceptOrderInv.setText("ACCEPT");
        btnacceptOrderInv.setPreferredSize(new java.awt.Dimension(156, 43));
        btnacceptOrderInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacceptOrderInvActionPerformed(evt);
            }
        });
        add(btnacceptOrderInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 130, 30));

        btndeclineOrderInv.setBackground(new java.awt.Color(52, 7, 116));
        btndeclineOrderInv.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btndeclineOrderInv.setForeground(new java.awt.Color(255, 255, 255));
        btndeclineOrderInv.setText("DECLINE");
        btndeclineOrderInv.setPreferredSize(new java.awt.Dimension(156, 43));
        btndeclineOrderInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeclineOrderInvActionPerformed(evt);
            }
        });
        add(btndeclineOrderInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 130, 30));

        enterpriseLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-inventory-48.png"))); // NOI18N
        enterpriseLabel.setText("COMPLETE ORDER");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 280, 50));

        btnBackCO.setBackground(new java.awt.Color(52, 7, 116));
        btnBackCO.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBackCO.setForeground(new java.awt.Color(255, 255, 255));
        btnBackCO.setText("<<");
        btnBackCO.setPreferredSize(new java.awt.Dimension(80, 30));
        btnBackCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCOActionPerformed(evt);
            }
        });
        add(btnBackCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventory001.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 70, 400, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void txtInventoryItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInventoryItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInventoryItemsActionPerformed

    private void btnacceptOrderInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacceptOrderInvActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblInventoryOrder.getSelectedRow();
//        System.out.println("Status "+InventoryTable.getValueAt(selectedRow, 3));
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "You must select a row first!");
        } else {
            if (tblInventoryOrder.getValueAt(selectedRow, 3).equals("Completed")) {
                JOptionPane.showMessageDialog(null, "Order is already completed!");
            } else {
                WorkRequest request = (WorkRequest) tblInventoryOrder.getValueAt(selectedRow, 0);
                request.setStatus("Accepted");
                populatetable();
            }

        }
        
    }//GEN-LAST:event_btnacceptOrderInvActionPerformed

    private void btndeclineOrderInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeclineOrderInvActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblInventoryOrder.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "You must select a row first!");
        }

        WorkRequest request = (WorkRequest) tblInventoryOrder.getValueAt(selectedRow, 0);
        if (tblInventoryOrder.getValueAt(selectedRow, 1).equals("Completed")) {
            JOptionPane.showMessageDialog(null, "Order is already processed and completed!");
        } else {

            request.setStatus("Declined");
            populatetable();
        }
                 
    }//GEN-LAST:event_btndeclineOrderInvActionPerformed

    private void btnBackCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCOActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackCOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackCO;
    private javax.swing.JButton btnacceptOrderInv;
    private javax.swing.JButton btndeclineOrderInv;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventoryOrder;
    private javax.swing.JTextField txtDateOrderedInventory;
    private javax.swing.JTextField txtInventoryItems;
    // End of variables declaration//GEN-END:variables
   
    
    
    private void populatetable(){
        DefaultTableModel dtm = (DefaultTableModel) tblInventoryOrder.getModel();
        dtm.setRowCount(0);

                Object row[] = new Object[4];
                row[0] = request;
                row[1] = request.getInventoryList().toString();
                row[2] = request.getRequestDate();
                row[3] = request.getStatus();

                dtm.addRow(row);
                        
    }
    
//    
//    public void populateComboBox(){
//        // MSS check
//                 for(Enterprise res: business.getEnterpriseDirectory().getEnterpriseList()){
//
////         for(Enterprise res: system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().getEnterpriseList()){
//             if(res.getEnterpriseType().getValue().equals("Delivery")){
//            delManCombo.addItem(res.getName());
//         
//        }else{
//                 System.out.println("nothing");
//             }
//         }
//    }
    
}

