/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.EcoSystem;
import Business.Enterprise;
import Business.InsuranceAdmin.InsuranceAdminDirectory;
import Business.InsuranceAdmin.InsurancePlan;
import Business.InsuranceAdmin.InsuranceeAdmin;
import Business.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BuyInsuranceWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Soumya
 */

public class ViewInsurancePlans extends javax.swing.JPanel {

    /**
     * Creates new form ViewInsurancePlans
     */
    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount userAccount;
    InsuranceAdminDirectory id;
    InsuranceeAdmin ic;
    String name;
    public ViewInsurancePlans(JPanel userProcessContainer,UserAccount userAccount,EcoSystem business) {
        initComponents();
        this.userAccount=userAccount;
        this.userProcessContainer = userProcessContainer;
        this.business = business;
//        id= system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise();
        insuranceCompanyJComboBox.removeAllItems();
//        populateInsuranceJComboBox(id);
        populateLogComboBox();
        btnPayIns.setVisible(false);
        
    }
   
//  

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        insuranceCompanyJComboBox = new javax.swing.JComboBox<>();
        btnPayIns = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInsCompanyPlans = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPlannameField = new javax.swing.JTextField();
        txtyrsDurationfield = new javax.swing.JTextField();
        txtmonthfiels = new javax.swing.JTextField();
        txttotalamtIns = new javax.swing.JTextField();
        btnviewPlans = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnCheckPlans = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setText("SELECT COMPANY: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        insuranceCompanyJComboBox.setForeground(new java.awt.Color(255, 255, 255));
        insuranceCompanyJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        insuranceCompanyJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceCompanyJComboBoxActionPerformed(evt);
            }
        });
        add(insuranceCompanyJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 130, -1));

        btnPayIns.setBackground(new java.awt.Color(52, 7, 116));
        btnPayIns.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnPayIns.setForeground(new java.awt.Color(255, 255, 255));
        btnPayIns.setText("Pay");
        btnPayIns.setPreferredSize(new java.awt.Dimension(156, 43));
        btnPayIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayInsActionPerformed(evt);
            }
        });
        add(btnPayIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, -1, -1));

        tblInsCompanyPlans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Insurance Plan Name", "Total years", "Monthly premium amount", "Total amount"
            }
        ));
        tblInsCompanyPlans.setGridColor(new java.awt.Color(255, 255, 255));
        tblInsCompanyPlans.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblInsCompanyPlans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInsCompanyPlansMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInsCompanyPlans);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 630, 150));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setText("Plan Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 7, 116));
        jLabel4.setText("Total years of duration:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 160, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setText("Monthly premium amount:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 7, 116));
        jLabel6.setText("Total premium amount:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, -1, -1));

        txtPlannameField.setEditable(false);
        txtPlannameField.setPreferredSize(new java.awt.Dimension(164, 30));
        txtPlannameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlannameFieldActionPerformed(evt);
            }
        });
        add(txtPlannameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 160, -1));

        txtyrsDurationfield.setEditable(false);
        txtyrsDurationfield.setPreferredSize(new java.awt.Dimension(164, 30));
        txtyrsDurationfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyrsDurationfieldActionPerformed(evt);
            }
        });
        add(txtyrsDurationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 160, -1));

        txtmonthfiels.setEditable(false);
        txtmonthfiels.setPreferredSize(new java.awt.Dimension(164, 30));
        txtmonthfiels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmonthfielsActionPerformed(evt);
            }
        });
        add(txtmonthfiels, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 160, -1));

        txttotalamtIns.setEditable(false);
        txttotalamtIns.setPreferredSize(new java.awt.Dimension(164, 30));
        txttotalamtIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalamtInsActionPerformed(evt);
            }
        });
        add(txttotalamtIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 160, -1));

        btnviewPlans.setBackground(new java.awt.Color(52, 7, 116));
        btnviewPlans.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnviewPlans.setForeground(new java.awt.Color(255, 255, 255));
        btnviewPlans.setText("VIEW PLANS");
        btnviewPlans.setPreferredSize(new java.awt.Dimension(156, 43));
        btnviewPlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewPlansActionPerformed(evt);
            }
        });
        add(btnviewPlans, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-medical-id-64.png"))); // NOI18N
        enterpriseLabel.setText("INSURANCE COMPANIES AND PLANS");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 490, 70));

        jButton6.setBackground(new java.awt.Color(52, 7, 116));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<<");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, -1));

        btnCheckPlans.setBackground(new java.awt.Color(52, 7, 116));
        btnCheckPlans.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCheckPlans.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckPlans.setText("Check Plans");
        btnCheckPlans.setPreferredSize(new java.awt.Dimension(156, 43));
        btnCheckPlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPlansActionPerformed(evt);
            }
        });
        add(btnCheckPlans, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insuranceImg.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 970, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void insuranceCompanyJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceCompanyJComboBoxActionPerformed
        // TODO add your handling code here:

        int selectedValue = insuranceCompanyJComboBox.getSelectedIndex();
        name = insuranceCompanyJComboBox.getItemAt(selectedValue);
        //        populatePlans(name);

    }//GEN-LAST:event_insuranceCompanyJComboBoxActionPerformed

    private void btnPayInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayInsActionPerformed
      // TODO add your handling code here:
       
        ic = business.getEnterpriseDirectory().findEnterprise(name).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(name);
        
        int rowCount = tblInsCompanyPlans.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            InsurancePlan ip = (InsurancePlan) tblInsCompanyPlans.getValueAt(i, 0);
             ic.getOrderedPlanDirectory().addPlan(ip);
           // ic.getInsurancePlanDirectory().addPlan(ip);
        }
        //        System.out.println(lab.getTestlist().getTestList());
        Boolean flag = true;
        if (ic.getInsurancePlanDirectory().getIpDirectory().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: There are no plans chosen!");
            flag = false;
        } else {

            BuyInsuranceWorkRequest buyInsuranceRequest = new BuyInsuranceWorkRequest();
            
            InsurancePlan ip = (InsurancePlan) tblInsCompanyPlans.getValueAt(0, 0);
            buyInsuranceRequest.setSender(this.userAccount);
            buyInsuranceRequest.setPlan(ip);
           
            int selectedValue = insuranceCompanyJComboBox.getSelectedIndex();

            InsuranceeAdmin  icc = business.getEnterpriseDirectory().findEnterprise(name).getOrganizationDirectory().getInsuranceAdminDirectory().getInsuranceList().get(selectedValue);

            buyInsuranceRequest.setReceiver(business.getUserAccountDirectory().findUserAccount(icc.getName()));
            buyInsuranceRequest.setRequestDate(new Date());
            buyInsuranceRequest.setStatus("Insurance ordered");
            business.getWorkQueue().addWorkRequest(buyInsuranceRequest);

        }

        if (flag) {
            JOptionPane.showMessageDialog(null, "Insurance ordered successfully! Thank you for your payment");
            System.out.println(userAccount.getWorkQueue().getWorkRequestList());
            //            System.out.println("prev");
            List<WorkRequest> r = this.userAccount.getWorkQueue().getWorkRequestList();

            ViewCurrentPlans view = new ViewCurrentPlans(userProcessContainer, userAccount, business);
            userProcessContainer.add("ViewPlans", view);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }


    }//GEN-LAST:event_btnPayInsActionPerformed

    private void tblInsCompanyPlansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInsCompanyPlansMouseClicked
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) tblInsCompanyPlans.getModel();

        String name = dtm.getValueAt(tblInsCompanyPlans.getSelectedRow(), 0).toString();
        int years = Integer.parseInt(dtm.getValueAt(tblInsCompanyPlans.getSelectedRow(), 1).toString());
        Double monthlyPremiumAmount = Double.parseDouble(dtm.getValueAt(tblInsCompanyPlans.getSelectedRow(), 2).toString());
        Double totalAmount = Double.parseDouble(dtm.getValueAt(tblInsCompanyPlans.getSelectedRow(), 3).toString());

        txtPlannameField.setText(name);
        txtyrsDurationfield.setText(String.valueOf(years));
        txtmonthfiels.setText(String.valueOf(monthlyPremiumAmount));
        txttotalamtIns.setText(String.valueOf(totalAmount));
        btnPayIns.setVisible(true);
    }//GEN-LAST:event_tblInsCompanyPlansMouseClicked

    private void txtPlannameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlannameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlannameFieldActionPerformed

    private void txtyrsDurationfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyrsDurationfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyrsDurationfieldActionPerformed

    private void txtmonthfielsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmonthfielsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmonthfielsActionPerformed

    private void txttotalamtInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalamtInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalamtInsActionPerformed

    private void btnviewPlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewPlansActionPerformed
        // TODO add your handling code here:
            ViewCurrentPlans viewCurrentPlans = new ViewCurrentPlans(userProcessContainer, userAccount, business);
            userProcessContainer.add("viewCurentPlans", viewCurrentPlans);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

    }//GEN-LAST:event_btnviewPlansActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnCheckPlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPlansActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnCheckPlansActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckPlans;
    private javax.swing.JButton btnPayIns;
    private javax.swing.JButton btnviewPlans;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JComboBox<String> insuranceCompanyJComboBox;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInsCompanyPlans;
    private javax.swing.JTextField txtPlannameField;
    private javax.swing.JTextField txtmonthfiels;
    private javax.swing.JTextField txttotalamtIns;
    private javax.swing.JTextField txtyrsDurationfield;
    // End of variables declaration//GEN-END:variables


    private void populateTable() {
         //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel dtm = (DefaultTableModel) tblInsCompanyPlans.getModel();
        dtm.setRowCount(0);
        int selectedValue = insuranceCompanyJComboBox.getSelectedIndex();
        String Admin = insuranceCompanyJComboBox.getItemAt(selectedValue);
        System.out.println("name"+name);
        System.out.println("insur"+Admin);
        // MSS check
//        InsuranceeAdmin ic = system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(name).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(Admin);
        InsuranceeAdmin ic = business.getEnterpriseDirectory().findEnterprise(name).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(Admin);

//        System.out.println("Lab in table is "+lab.getName());

        for (InsurancePlan p : ic.getInsurancePlanDirectory().getIpDirectory()) {
            {
                Object[] row = new Object[4];
                row[0] = p;
                row[1] = p.getTotalYears();
                row[2] = p.getMonthlyPremium();
                row[3] = p.getTotalPremium();
                dtm.addRow(row);
            }
    }
    }

//    private void populatePlans(String name) {
//            for (InsuranceeAdmin ic : system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(name).getOrganizationDirectory().getInsuranceAdminDirectory().getInsuranceList()) {
//            if (ic.getName().equals(name)) {
//                InsuranceeAdmin ic1 = ic;
//                for (InsurancePlan ip :ic1.getInsurancePlanDirectory().getIpDirectory() ) {
//                    insuranceCompanyJComboBox.addItem(ip.getName());
//                }
//                break;
//            }
//        }
//    }
     private void populateLogComboBox() {
         // MSS check
//      for(Enterprise res: system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().getEnterpriseList()){
      for(Enterprise res: business.getEnterpriseDirectory().getEnterpriseList()){
             
if(res.getEnterpriseType().getValue().equals("Insurance")){
                            insuranceCompanyJComboBox.addItem(res.getName());
         
        }else{
                 System.out.println("No Companies");
             }
        }
    }
}

