/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAdmin;

import Business.EcoSystem;
import Business.InsuranceAdmin.InsurancePlan;
import Business.InsuranceAdmin.InsurancePlanDirectory;
import Business.InsuranceAdmin.InsuranceeAdmin;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Malini
 */

public class AddInsurancePlanJPanel extends javax.swing.JPanel {
    
     /**
     * Creates new form AddInsurancePlanJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem business;
    
    UserAccount userAccount;
    InsuranceeAdmin ic;
    
    
public AddInsurancePlanJPanel(JPanel userProcessContainer,UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.userAccount= userAccount;
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtyrsField = new javax.swing.JTextField();
        txtMonthlField = new javax.swing.JTextField();
        txttotalField = new javax.swing.JTextField();
        btnAddInsPlan = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Plan Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total years of duration:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 190, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 7, 116));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Monthly premium amount:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 20));

        txtnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameFieldActionPerformed(evt);
            }
        });
        add(txtnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 190, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Total premium amount:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        txtyrsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyrsFieldActionPerformed(evt);
            }
        });
        add(txtyrsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 190, 30));

        txtMonthlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthlFieldActionPerformed(evt);
            }
        });
        add(txtMonthlField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 190, 30));

        txttotalField.setEditable(false);
        txttotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalFieldActionPerformed(evt);
            }
        });
        add(txttotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 190, 30));

        btnAddInsPlan.setBackground(new java.awt.Color(52, 7, 116));
        btnAddInsPlan.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAddInsPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnAddInsPlan.setText("ADD PLAN");
        btnAddInsPlan.setPreferredSize(new java.awt.Dimension(156, 43));
        btnAddInsPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInsPlanActionPerformed(evt);
            }
        });
        add(btnAddInsPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 130, 30));

        enterpriseLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-medical-history-64.png"))); // NOI18N
        enterpriseLabel.setText("ADD INSURANCE PLAN");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 400, 60));

        jButton6.setBackground(new java.awt.Color(52, 7, 116));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<<");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insuranceImage2.jpg"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 690, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameFieldActionPerformed

    private void txtyrsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyrsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyrsFieldActionPerformed

    private void txtMonthlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthlFieldActionPerformed

    private void txttotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalFieldActionPerformed

    private void btnAddInsPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInsPlanActionPerformed
        // TODO add your handling code here:
        if (txtnameField.getText().isEmpty() || txtyrsField.getText().isEmpty() || txtMonthlField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all details of the Insurance Plan");
            return;
        } else {
            if (!txtnameField.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper Insurance Plan name");
                txtnameField.setText("");
                return;
            } else if (!txtyrsField.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Enter proper Years duration in integers");
                txtyrsField.setText("");
                return;
            }    else if (!txtMonthlField.getText().matches("^-?\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Enter monthly premium rate like 14.3");
                txtMonthlField.setText("");
                return;
            }
            double totalAmount = Double.parseDouble(txtMonthlField.getText()) * Integer.parseInt(txtyrsField.getText());
            txttotalField.setText(String.valueOf(totalAmount));
            InsurancePlan i = new InsurancePlan(txtnameField.getText(),Integer.parseInt(txtyrsField.getText()),Double.parseDouble(txtMonthlField.getText()),Double.parseDouble(txttotalField.getText()));
            // MSS check
//            ic = system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(userAccount.getEmployee().getName());
            ic = business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(userAccount.getEmployee().getName());
            
            if(ic.getInsurancePlanDirectory()==null ||ic ==null){

                InsurancePlanDirectory pd = new InsurancePlanDirectory();
                ArrayList<InsurancePlan> am  = new ArrayList<>();
                am.add(i);
                pd.setIpDirectory(am);
                ic.setInsurancePlanDirectory(pd);
                JOptionPane.showMessageDialog(null, "Added insurance plan");

            }else{
                InsurancePlanDirectory pd = ic.getInsurancePlanDirectory();
                ArrayList<InsurancePlan> am  = ic.getInsurancePlanDirectory().getIpDirectory();
                am.add(i);
                pd.setIpDirectory(am);
                ic.setInsurancePlanDirectory(pd);
                JOptionPane.showMessageDialog(null, "Added insurance plan");
            }

            //               this.userAccount.getRole();

        }
        // JOptionPane.showMessageDialog(null, "Insurance plan added successfully");
        txtnameField.setText("");
        txtyrsField.setText("");
        txtMonthlField.setText("");
        txttotalField.setText("");
        
    }//GEN-LAST:event_btnAddInsPlanActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInsPlan;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtMonthlField;
    private javax.swing.JTextField txtnameField;
    private javax.swing.JTextField txttotalField;
    private javax.swing.JTextField txtyrsField;
    // End of variables declaration//GEN-END:variables
}
