/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAdmin;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BuyInsuranceWorkRequest;
import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Malini
 */
public class ConfirmInsuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmInsuranceJPanel
     */
    
    
    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount userAccount;
    BuyInsuranceWorkRequest buyInsurance;
    
    public ConfirmInsuranceJPanel(JPanel userProcessContainer,UserAccount userAccount, EcoSystem business, BuyInsuranceWorkRequest buyInsurance) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount= userAccount;
        this.business=business;
        this.buyInsurance = buyInsurance;
        txtPname.setText(buyInsurance.getSender().getEmployee().getName());
        txtplanName.setText(buyInsurance.getPlan().getName());
        txtyrsField.setText(String.valueOf(buyInsurance.getPlan().getTotalYears()));
        txtmonthfield.setText(String.valueOf(buyInsurance.getPlan().getMonthlyPremium()));
        txttotalField.setText(String.valueOf(buyInsurance.getPlan().getTotalPremium()));
        txtpurchaseDate.setText(String.valueOf(buyInsurance.getRequestDate()));
        Calendar c = Calendar.getInstance();
        c.setTime(buyInsurance.getRequestDate());
        c.add(Calendar.YEAR, buyInsurance.getPlan().getTotalYears());
        Date validity = c.getTime();
        txtvalidity.setText(String.valueOf(validity));
        txtStatus.setText(buyInsurance.getStatus());
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtplanName = new javax.swing.JTextField();
        txtyrsField = new javax.swing.JTextField();
        txtmonthfield = new javax.swing.JTextField();
        txttotalField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpurchaseDate = new javax.swing.JTextField();
        txtvalidity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        btnconfirmInsPurchase = new javax.swing.JButton();
        btndeclineInsPurchase = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));
        add(txtPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 170, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Plan Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        txtplanName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplanNameActionPerformed(evt);
            }
        });
        add(txtplanName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 170, 30));

        txtyrsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyrsFieldActionPerformed(evt);
            }
        });
        add(txtyrsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 170, 30));
        add(txtmonthfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 170, 30));
        add(txttotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 170, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 7, 116));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total Years duration:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Monthly Premium Amount:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 7, 116));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Total Premium Amount:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 7, 116));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Purchased on:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(52, 7, 116));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Validity:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));
        add(txtpurchaseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 170, 30));
        add(txtvalidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 170, 30));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(52, 7, 116));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Status:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 170, 30));

        btnconfirmInsPurchase.setBackground(new java.awt.Color(52, 7, 116));
        btnconfirmInsPurchase.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnconfirmInsPurchase.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirmInsPurchase.setText("Confirm Purchase");
        btnconfirmInsPurchase.setPreferredSize(new java.awt.Dimension(156, 43));
        btnconfirmInsPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmInsPurchaseActionPerformed(evt);
            }
        });
        add(btnconfirmInsPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 180, 30));

        btndeclineInsPurchase.setBackground(new java.awt.Color(52, 7, 116));
        btndeclineInsPurchase.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btndeclineInsPurchase.setForeground(new java.awt.Color(255, 255, 255));
        btndeclineInsPurchase.setText("Decline purchase");
        btndeclineInsPurchase.setPreferredSize(new java.awt.Dimension(156, 43));
        btndeclineInsPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeclineInsPurchaseActionPerformed(evt);
            }
        });
        add(btndeclineInsPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 180, 30));

        jButton6.setBackground(new java.awt.Color(52, 7, 116));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<<");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-medical-history-64.png"))); // NOI18N
        enterpriseLabel.setText("CONFIRM INSURANCE");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 460, 50));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 7, 116));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insuranceImage2.jpg"))); // NOI18N
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 690, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void txtplanNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplanNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplanNameActionPerformed

    private void txtyrsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyrsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyrsFieldActionPerformed

    private void btnconfirmInsPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmInsPurchaseActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this, " Purchase confirmed");
        buyInsurance.setStatus("Purchase confirmed");
        buyInsurance.getSender().getEmployee().setHasInsurance(true);
        txtStatus.setText(buyInsurance.getStatus());
        
    }//GEN-LAST:event_btnconfirmInsPurchaseActionPerformed

    private void btndeclineInsPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeclineInsPurchaseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, " Purchase declined! If money deducted refund will be initiated");
        buyInsurance.setStatus("Purchase declined : refund initiated");
        buyInsurance.getSender().getEmployee().setHasInsurance(false);
        txtStatus.setText(buyInsurance.getStatus());
        
    }//GEN-LAST:event_btndeclineInsPurchaseActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfirmInsPurchase;
    private javax.swing.JButton btndeclineInsPurchase;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtPname;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtmonthfield;
    private javax.swing.JTextField txtplanName;
    private javax.swing.JTextField txtpurchaseDate;
    private javax.swing.JTextField txttotalField;
    private javax.swing.JTextField txtvalidity;
    private javax.swing.JTextField txtyrsField;
    // End of variables declaration//GEN-END:variables
}
