/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAdmin;


import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BuyInsuranceWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Malini
 */
public class ManageInsuranceOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInsuranceOrdersJPanel
     */
     JPanel userProcessContainer;
    EcoSystem business;
    UserAccount userAccount;
    public ManageInsuranceOrdersJPanel(JPanel userProcessContainer,UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount= userAccount;
        this.business=business;
        populateTable();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblinsurance = new javax.swing.JTable();
        btnViewDetIO = new javax.swing.JButton();
        btnRefreshIO = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblinsurance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ordered By", "Plan Name", "Ordered On", "Status"
            }
        ));
        tblinsurance.setGridColor(new java.awt.Color(255, 255, 255));
        tblinsurance.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblinsurance);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 409, 100));

        btnViewDetIO.setBackground(new java.awt.Color(52, 7, 116));
        btnViewDetIO.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnViewDetIO.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetIO.setText("View details");
        btnViewDetIO.setPreferredSize(new java.awt.Dimension(156, 43));
        btnViewDetIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetIOActionPerformed(evt);
            }
        });
        add(btnViewDetIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 130, 30));

        btnRefreshIO.setBackground(new java.awt.Color(52, 7, 116));
        btnRefreshIO.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnRefreshIO.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshIO.setText("Refresh");
        btnRefreshIO.setPreferredSize(new java.awt.Dimension(156, 43));
        btnRefreshIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshIOActionPerformed(evt);
            }
        });
        add(btnRefreshIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 130, 30));

        jButton4.setBackground(new java.awt.Color(52, 7, 116));
        jButton4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("<<");
        jButton4.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-medical-insurance-64.png"))); // NOI18N
        enterpriseLabel.setText("MANGE INSURANCE  ORDERS");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 350, 70));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insuranceImage2.jpg"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 690, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetIOActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblinsurance.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");

        } else {
            WorkRequest request = (WorkRequest) tblinsurance.getValueAt(selectedRow, 0);
            //            System.out.println(workRequestJTable.getValueAt(selectedRow, 1));
            //            System.out.println(workRequestJTable.getValueAt(selectedRow, 0));
            //            System.out.println((request instanceof PlaceNewOrderWorkRequest));
            if (request instanceof BuyInsuranceWorkRequest) {
                BuyInsuranceWorkRequest buyInsuranceWorkRequest = (BuyInsuranceWorkRequest) tblinsurance.getValueAt(selectedRow, 0);
                System.out.println(buyInsuranceWorkRequest.getClass());
                if (buyInsuranceWorkRequest != null) {
                    System.out.println("Is it null");
                    ConfirmInsuranceJPanel confirmInsurance = new ConfirmInsuranceJPanel(userProcessContainer, userAccount, business, buyInsuranceWorkRequest);
                    userProcessContainer.add("CompleteTestJPanel", confirmInsurance);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                } else {
                    System.out.println("its null");
                }
            }
        }
    }//GEN-LAST:event_btnViewDetIOActionPerformed

    private void btnRefreshIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshIOActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshIOActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshIO;
    private javax.swing.JButton btnViewDetIO;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblinsurance;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
        //To change body of generated methods, choose Tools | Templates.
                System.out.println("Its entering over here");
        DefaultTableModel model = (DefaultTableModel) tblinsurance.getModel();
        model.setRowCount(0);
//        System.out.println("R is");
        System.out.println(business.getWorkQueue().getWorkRequestList());
        for (WorkRequest request : business.getWorkQueue().getWorkRequestList()) {
            if(request instanceof BuyInsuranceWorkRequest){
            BuyInsuranceWorkRequest buyInsurance = (BuyInsuranceWorkRequest ) request;
//            System.out.println("REC "+request.getReceiver().getUsername());
//            System.out.println("class: " +request.getSender().getUsername());
//            System.out.println("class: " +request.getSender().getPassword());
//            System.out.println("HELLO "+this.userAccount);
            
            if (request.getReceiver().getUsername().equals(this.userAccount.getUsername())) {
                Object[] row = new Object[4];
                row[0] = request;
                row[1] = buyInsurance.getPlan().getName();
                row[2] = request.getRequestDate();
                row[3] = request.getStatus();
                model.addRow(row);
            }
    }}
    }
}

