package userinterface.InsuranceAdmin;



import Business.EcoSystem;
import Business.InsuranceAdmin.InsurancePlan;
import Business.InsuranceAdmin.InsuranceeAdmin;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Soumya
 */
public class ViewUpdateDeleteIPlansJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdateDeleteIPlansJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount userAccount;
     
    InsuranceeAdmin ic;
    public ViewUpdateDeleteIPlansJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem business) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        
        // MSS check
//        if(system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(userAccount.getEmployee().getName()).getInsurancePlanDirectory()!=null ){
        if(business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(userAccount.getEmployee().getName()).getInsurancePlanDirectory()!=null ){      
            populateTable();
        }else{
             JOptionPane.showMessageDialog(null, "No Insurance Plan added");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtmonthPlans = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplans = new javax.swing.JTable();
        txtNamePlans = new javax.swing.JTextField();
        txtyrsPlans = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnUpdatePlans = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        txttotalpremPlans = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnDeleteMI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 7, 116));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Monthly premium amount:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 200, -1));

        txtmonthPlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmonthPlansActionPerformed(evt);
            }
        });
        add(txtmonthPlans, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 180, 30));

        tblplans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Insurance Plan Name", "Total years", "Monthly premium amount", "Total amount"
            }
        ));
        tblplans.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblplans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplansMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblplans);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 540, 130));

        txtNamePlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamePlansActionPerformed(evt);
            }
        });
        add(txtNamePlans, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 180, 30));

        txtyrsPlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyrsPlansActionPerformed(evt);
            }
        });
        add(txtyrsPlans, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 180, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total years of duration:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 180, -1));

        btnUpdatePlans.setBackground(new java.awt.Color(52, 7, 116));
        btnUpdatePlans.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnUpdatePlans.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdatePlans.setText("UPDATE");
        btnUpdatePlans.setPreferredSize(new java.awt.Dimension(156, 43));
        btnUpdatePlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePlansActionPerformed(evt);
            }
        });
        add(btnUpdatePlans, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 130, 30));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-medical-history-64.png"))); // NOI18N
        enterpriseLabel.setText("MANAGE INSURANCE");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 320, 60));

        txttotalpremPlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalpremPlansActionPerformed(evt);
            }
        });
        add(txttotalpremPlans, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 180, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Total premium amount:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 440, 180, -1));

        btnDeleteMI.setBackground(new java.awt.Color(52, 7, 116));
        btnDeleteMI.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnDeleteMI.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteMI.setText("DELETE");
        btnDeleteMI.setPreferredSize(new java.awt.Dimension(156, 43));
        btnDeleteMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMIActionPerformed(evt);
            }
        });
        add(btnDeleteMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 110, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Plan Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 100, -1));

        jButton6.setBackground(new java.awt.Color(52, 7, 116));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<<");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insuranceImage001.jpg"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 580, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void txtmonthPlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmonthPlansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmonthPlansActionPerformed

    private void tblplansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplansMouseClicked
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) tblplans.getModel();

        String name = dtm.getValueAt(tblplans.getSelectedRow(), 0).toString();
        int years = Integer.parseInt(dtm.getValueAt(tblplans.getSelectedRow(), 1).toString());
        Double monthlyPremiumAmount = Double.parseDouble(dtm.getValueAt(tblplans.getSelectedRow(), 2).toString());
        Double totalAmount = Double.parseDouble(dtm.getValueAt(tblplans.getSelectedRow(), 3).toString());

        txtNamePlans.setText(name);
        txtyrsPlans.setText(String.valueOf(years));
        txtmonthPlans.setText(String.valueOf(monthlyPremiumAmount));
        txttotalpremPlans.setText(String.valueOf(totalAmount));
    }//GEN-LAST:event_tblplansMouseClicked

    private void txtNamePlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamePlansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamePlansActionPerformed

    private void txtyrsPlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyrsPlansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyrsPlansActionPerformed

    private void btnUpdatePlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePlansActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblplans.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        } else {
            //            updateJPanel.setVisible(true);
            if (!txtNamePlans.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper Insurance Plan name");
                txtNamePlans.setText("");
                return;
            } else if (!txtyrsPlans.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Enter proper Years duration in integers");
                txtyrsPlans.setText("");
                return;
            }    else if (!txtmonthPlans.getText().matches("^-?\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Enter monthly premium rate like 14.3");
                txtmonthPlans.setText("");
                return;
            }
            InsurancePlan ip = (InsurancePlan) tblplans.getValueAt(selectedRow, 0);
            //            System.out.println("item : " + t.getName());
            ip.setName(txtNamePlans.getText());
            ip.setTotalYears(Integer.parseInt(txtyrsPlans.getText()));
            ip.setMonthlyPremium(Double.parseDouble(txtmonthPlans.getText()));
            ip.setTotalPremium();
            populateTable();
            txtNamePlans.setText("");
            txtyrsPlans.setText("");
            txtmonthPlans.setText("");
            txttotalpremPlans.setText("");

        }
        
    }//GEN-LAST:event_btnUpdatePlansActionPerformed

    private void txttotalpremPlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalpremPlansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalpremPlansActionPerformed

    private void btnDeleteMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMIActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblplans.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");

        } else {
            InsurancePlan ip = (InsurancePlan) tblplans.getValueAt(selectedRow, 0);
            // MSS check
//            ic = system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(this.userAccount.getEmployee().getName());
                        ic = business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(this.userAccount.getEmployee().getName());

            System.out.println(ic);
            ic.getInsurancePlanDirectory().deleteInsuranceCompany(ip);
            JOptionPane.showMessageDialog(null, "Insurance Plan " + txtNamePlans.getText() + " deleted");
            populateTable();
            txtNamePlans.setText("");
            txtNamePlans.setText("");
            txtyrsPlans.setText("");
            txtmonthPlans.setText("");
            txttotalpremPlans.setText("");

        }
        
    }//GEN-LAST:event_btnDeleteMIActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteMI;
    private javax.swing.JButton btnUpdatePlans;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblplans;
    private javax.swing.JTextField txtNamePlans;
    private javax.swing.JTextField txtmonthPlans;
    private javax.swing.JTextField txttotalpremPlans;
    private javax.swing.JTextField txtyrsPlans;
    // End of variables declaration//GEN-END:variables

 private void populateTable() {
        
                DefaultTableModel model = (DefaultTableModel) tblplans.getModel();
        model.setRowCount(0);
        // MSS check
//        ic =system.findNetwork(userAccount.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(this.userAccount.getEmployee().getName());
        ic =business.getEnterpriseDirectory().findEnterprise(userAccount.getEmployee().getName()).getOrganizationDirectory().getInsuranceAdminDirectory().findInsuranceAdmin(this.userAccount.getEmployee().getName());
            
        if(ic.getInsurancePlanDirectory().getIpDirectory()==null){
                JOptionPane.showMessageDialog(null, "Please add a plan");
            return;
               }else{
            for(InsurancePlan ip: ic.getInsurancePlanDirectory().getIpDirectory()){
            Object[] row = new Object[4];
            row[0] = ip;
            row[1] = ip.getTotalYears();
            row[2] = ip.getMonthlyPremium();
            row[3] = ip.getTotalPremium();

            model.addRow(row);
                       }
        }
    
    }
}
