/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceAdmin;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Malini
 */
public class InsuranceAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceAdminJPanel
     */
   JPanel userProcessContainer;
    EcoSystem business;
    UserAccount user;
    public InsuranceAdminJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount user) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.user = user;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngInsPlan = new javax.swing.JButton();
        btnMngEmployee = new javax.swing.JButton();
        btnMngOrders = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMngInsPlan.setBackground(new java.awt.Color(52, 7, 116));
        btnMngInsPlan.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMngInsPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnMngInsPlan.setText("Manage Insurance Plan");
        btnMngInsPlan.setPreferredSize(new java.awt.Dimension(156, 43));
        btnMngInsPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngInsPlanActionPerformed(evt);
            }
        });
        add(btnMngInsPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 210, -1));

        btnMngEmployee.setBackground(new java.awt.Color(52, 7, 116));
        btnMngEmployee.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMngEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnMngEmployee.setText("Add new Insurance");
        btnMngEmployee.setPreferredSize(new java.awt.Dimension(156, 43));
        btnMngEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngEmployeeActionPerformed(evt);
            }
        });
        add(btnMngEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 210, -1));

        btnMngOrders.setBackground(new java.awt.Color(52, 7, 116));
        btnMngOrders.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMngOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnMngOrders.setText("Manage Insurace Orders");
        btnMngOrders.setPreferredSize(new java.awt.Dimension(156, 43));
        btnMngOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngOrdersActionPerformed(evt);
            }
        });
        add(btnMngOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 210, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-medical-insurance-64.png"))); // NOI18N
        enterpriseLabel.setText("INSURANCE ADMIN");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -10, 310, 90));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminIns - Copy.png"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 660, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngInsPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngInsPlanActionPerformed
        // TODO add your handling code here:
        ViewUpdateDeleteIPlansJPanel viewUpdateDeleteIPlansJPanel = new ViewUpdateDeleteIPlansJPanel(userProcessContainer, user, business);
        userProcessContainer.add("viewUpdateDeleteIPlans", viewUpdateDeleteIPlansJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngInsPlanActionPerformed

    private void btnMngEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngEmployeeActionPerformed
        AddInsurancePlanJPanel addInsurancePlanJPanel = new AddInsurancePlanJPanel(userProcessContainer, user, business);
        userProcessContainer.add("AddInusrance", addInsurancePlanJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngEmployeeActionPerformed

    private void btnMngOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngOrdersActionPerformed
        ManageInsuranceOrdersJPanel manageInsurancePlan = new ManageInsuranceOrdersJPanel(userProcessContainer, user, business);
        userProcessContainer.add("manageinsurance", manageInsurancePlan);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngEmployee;
    private javax.swing.JButton btnMngInsPlan;
    private javax.swing.JButton btnMngOrders;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
