/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Administrator;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise;
import Business.HospitalAdmin.Hospital;
import Business.Organization;
import Business.Role.HospitalAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Soumya
 */
public class AddHospital extends javax.swing.JPanel {

    /**
     * Creates new form AddHospital
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    
    public AddHospital(JPanel userProcessContainer, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHosName = new javax.swing.JTextField();
        txtHosAddr = new javax.swing.JTextField();
        txtHosUName = new javax.swing.JTextField();
        txtHosPwd = new javax.swing.JTextField();
        addHospitalBtn = new javax.swing.JButton();
        btnBackHos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboHosLoc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHosEmail = new javax.swing.JTextField();
        txtHosNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHosName.setPreferredSize(new java.awt.Dimension(15, 30));
        add(txtHosName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 164, -1));

        txtHosAddr.setPreferredSize(new java.awt.Dimension(15, 30));
        add(txtHosAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 164, -1));

        txtHosUName.setPreferredSize(new java.awt.Dimension(15, 30));
        add(txtHosUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 164, -1));

        txtHosPwd.setPreferredSize(new java.awt.Dimension(15, 30));
        add(txtHosPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 164, -1));

        addHospitalBtn.setBackground(new java.awt.Color(52, 7, 68));
        addHospitalBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        addHospitalBtn.setForeground(new java.awt.Color(255, 255, 255));
        addHospitalBtn.setText("Add Hospital");
        addHospitalBtn.setPreferredSize(new java.awt.Dimension(156, 43));
        addHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHospitalBtnActionPerformed(evt);
            }
        });
        add(addHospitalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 180, 40));

        btnBackHos.setBackground(new java.awt.Color(52, 7, 68));
        btnBackHos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBackHos.setForeground(new java.awt.Color(255, 255, 255));
        btnBackHos.setText("<<");
        btnBackHos.setPreferredSize(new java.awt.Dimension(80, 30));
        btnBackHos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackHosActionPerformed(evt);
            }
        });
        add(btnBackHos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 7, 116));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-hospital-64.png"))); // NOI18N
        jLabel1.setText("ADD HOSPITAL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 400, 70));

        comboHosLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brigham", "Cambridge", "Brookline", "Longwood", "Fenway" }));
        comboHosLoc.setPreferredSize(new java.awt.Dimension(140, 30));
        comboHosLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHosLocActionPerformed(evt);
            }
        });
        add(comboHosLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 170, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setText("Hospital Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setText("Address");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 7, 116));
        jLabel4.setText("Username");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 90, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 90, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 7, 116));
        jLabel6.setText("Location");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 60, -1));

        txtHosEmail.setPreferredSize(new java.awt.Dimension(15, 30));
        add(txtHosEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 164, -1));

        txtHosNum.setPreferredSize(new java.awt.Dimension(15, 30));
        add(txtHosNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 164, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(52, 7, 116));
        jLabel8.setText("Email");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 50, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(52, 7, 116));
        jLabel9.setText("Phone");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a3.jpg"))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 820, 970));
    }// </editor-fold>//GEN-END:initComponents

    private void addHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHospitalBtnActionPerformed
        // TODO add your handling code here:
        if (txtHosUName.getText().isEmpty() || txtHosPwd.getText().isEmpty() || txtHosName.getText().isEmpty() || txtHosAddr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter all mandatory fields");
        } else {

            if (!txtHosName.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper name! Name should be string!");
                txtHosName.setText("");
                return;
            }
            else if(!txtHosAddr.getText().matches("\\d+\\s+([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+)")) {
                JOptionPane.showMessageDialog(this, "Enter proper Address in the format of 123 abcd");
                txtHosAddr.setText("");
                return;
            }
            else if(!txtHosEmail.getText().matches("^(.+)@(.+)$")){
                JOptionPane.showMessageDialog(this, "Enter proper Email in the format of abc@gmail.com");
                txtHosEmail.setText("");
                return;
            }
            else if(!txtHosNum.getText().matches("^\\d{10}$")){
                JOptionPane.showMessageDialog(this, "Enter a 10 digit phone number");
                txtHosNum.setText("");
                return;
            }
            if (strongUsername() == false) {
                txtHosUName.setText("");
                JOptionPane.showMessageDialog(null, "Username should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
                return;
            } else {
                String userName = txtHosUName.getText();
            }
            if (strongPassword() == false) {
                txtHosPwd.setText("");
                JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
                return;
            } else {
            }
            
            String name = txtHosName.getText();
            String add = txtHosAddr.getText();
            String username = txtHosUName.getText();
            String pass = txtHosPwd.getText();
            Object selectedItem = comboHosLoc.getSelectedItem();

            String loc = selectedItem.toString();
            Employee emp = business.getEmployeeDirectory().createEmployee(name);
            emp.setLocation(loc);
            
            UserAccount account = business.getUserAccountDirectory().createUserAccount(username, pass, emp, new HospitalAdminRole());
            
            if (business.getEnterpriseDirectory().findEnterprise(name) == null) {
                business.getEnterpriseDirectory().createAndAddEnterprise(name, Enterprise.EnterpriseType.Hospital);
                JOptionPane.showMessageDialog(null, "Hospital created");
                txtHosName.setText("");
                txtHosAddr.setText("");
                txtHosEmail.setText("");
                txtHosNum.setText("");
                txtHosUName.setText("");
                txtHosPwd.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Hospital already exists");
            }
        }
    }//GEN-LAST:event_addHospitalBtnActionPerformed

    private void btnBackHosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackHosActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_btnBackHosActionPerformed

    private void comboHosLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHosLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHosLocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHospitalBtn;
    private javax.swing.JButton btnBackHos;
    private javax.swing.JComboBox<String> comboHosLoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtHosAddr;
    private javax.swing.JTextField txtHosEmail;
    private javax.swing.JTextField txtHosName;
    private javax.swing.JTextField txtHosNum;
    private javax.swing.JTextField txtHosPwd;
    private javax.swing.JTextField txtHosUName;
    // End of variables declaration//GEN-END:variables

 private boolean strongUsername() {
        Pattern pat = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m = pat.matcher(txtHosUName.getText());
        boolean boo = m.matches();
        return boo;
    }

    private boolean strongPassword() {
        Pattern pat1;
        pat1 = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m1 = pat1.matcher(txtHosPwd.getText());
        boolean bat1 = m1.matches();
        return bat1;
    }
}

