/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Administrator;

import userinterface.HospitalAdminRole.AddPatientJPanel;
import Business.EcoSystem;
import Business.Enterprise;

import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author Soumya
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount user;
    Enterprise enterprise;
    Organization organization;
    
    public AdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.user = user;

        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddHospital = new javax.swing.JButton();
        btnAddLabs = new javax.swing.JButton();
        btnMngLabs = new javax.swing.JButton();
        btnAddEmergency = new javax.swing.JButton();
        btnAddSup = new javax.swing.JButton();
        btnMngSup = new javax.swing.JButton();
        btnMngPharma = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnChartEnt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAddPharmacy = new javax.swing.JButton();
        btnMngEmer = new javax.swing.JButton();
        btnAddIns = new javax.swing.JButton();
        btnMngInsurance = new javax.swing.JButton();
        btnAddHospital1 = new javax.swing.JButton();
        btnAddLabs1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1825, 1000));
        jPanel2.setLayout(null);

        btnAddHospital.setBackground(new java.awt.Color(52, 7, 116));
        btnAddHospital.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddHospital.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHospital.setText("Add Hospital");
        btnAddHospital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddHospital);
        btnAddHospital.setBounds(220, 170, 190, 43);

        btnAddLabs.setBackground(new java.awt.Color(52, 7, 116));
        btnAddLabs.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddLabs.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLabs.setText("Add Lab");
        btnAddLabs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddLabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLabsActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddLabs);
        btnAddLabs.setBounds(430, 360, 190, 43);

        btnMngLabs.setBackground(new java.awt.Color(52, 7, 116));
        btnMngLabs.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMngLabs.setForeground(new java.awt.Color(255, 255, 255));
        btnMngLabs.setText("Manage Lab");
        btnMngLabs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMngLabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngLabsActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngLabs);
        btnMngLabs.setBounds(430, 420, 190, 43);

        btnAddEmergency.setBackground(new java.awt.Color(52, 7, 116));
        btnAddEmergency.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddEmergency.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmergency.setText("Add Emergency");
        btnAddEmergency.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmergencyActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddEmergency);
        btnAddEmergency.setBounds(640, 360, 190, 43);

        btnAddSup.setBackground(new java.awt.Color(52, 7, 116));
        btnAddSup.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddSup.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSup.setText("Add Supplier");
        btnAddSup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddSup);
        btnAddSup.setBounds(640, 170, 190, 43);

        btnMngSup.setBackground(new java.awt.Color(52, 7, 116));
        btnMngSup.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMngSup.setForeground(new java.awt.Color(255, 255, 255));
        btnMngSup.setText("Manage Supplier");
        btnMngSup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMngSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngSupActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngSup);
        btnMngSup.setBounds(640, 230, 190, 43);

        btnMngPharma.setBackground(new java.awt.Color(52, 7, 116));
        btnMngPharma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMngPharma.setForeground(new java.awt.Color(255, 255, 255));
        btnMngPharma.setText("Manage Pharmacy");
        btnMngPharma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMngPharma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngPharmaActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngPharma);
        btnMngPharma.setBounds(430, 230, 190, 43);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminDashboard_Icon.png"))); // NOI18N
        jLabel2.setText("ADMIN DASHBOARD");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(280, 10, 560, 70);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(-20, 140, 0, 0);

        btnChartEnt.setBackground(new java.awt.Color(52, 7, 116));
        btnChartEnt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnChartEnt.setForeground(new java.awt.Color(255, 255, 255));
        btnChartEnt.setText("Chart Enterprises ");
        btnChartEnt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChartEnt.setPreferredSize(new java.awt.Dimension(156, 43));
        btnChartEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChartEntActionPerformed(evt);
            }
        });
        jPanel2.add(btnChartEnt);
        btnChartEnt.setBounds(220, 230, 190, 43);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(20, 490, 380, 310);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(410, 460, 430, 340);

        btnAddPharmacy.setBackground(new java.awt.Color(52, 7, 116));
        btnAddPharmacy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddPharmacy.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPharmacy.setText("Add Pharmacy");
        btnAddPharmacy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPharmacyActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddPharmacy);
        btnAddPharmacy.setBounds(430, 170, 190, 43);

        btnMngEmer.setBackground(new java.awt.Color(52, 7, 116));
        btnMngEmer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMngEmer.setForeground(new java.awt.Color(255, 255, 255));
        btnMngEmer.setText("Manage Emergency");
        btnMngEmer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMngEmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngEmerActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngEmer);
        btnMngEmer.setBounds(640, 420, 190, 43);

        btnAddIns.setBackground(new java.awt.Color(52, 7, 116));
        btnAddIns.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddIns.setForeground(new java.awt.Color(255, 255, 255));
        btnAddIns.setText("Add Insurance");
        btnAddIns.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInsActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddIns);
        btnAddIns.setBounds(220, 360, 190, 43);

        btnMngInsurance.setBackground(new java.awt.Color(52, 7, 116));
        btnMngInsurance.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMngInsurance.setForeground(new java.awt.Color(255, 255, 255));
        btnMngInsurance.setText("Manage Insurance");
        btnMngInsurance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMngInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngInsuranceActionPerformed(evt);
            }
        });
        jPanel2.add(btnMngInsurance);
        btnMngInsurance.setBounds(220, 420, 190, 43);

        btnAddHospital1.setBackground(new java.awt.Color(52, 7, 116));
        btnAddHospital1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddHospital1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHospital1.setText("Add Hospital");
        btnAddHospital1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospital1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddHospital1);
        btnAddHospital1.setBounds(220, 170, 190, 43);

        btnAddLabs1.setBackground(new java.awt.Color(52, 7, 116));
        btnAddLabs1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddLabs1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLabs1.setText("Add Labs");
        btnAddLabs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLabs1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddLabs1);
        btnAddLabs1.setBounds(430, 360, 190, 43);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChartEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChartEntActionPerformed
        // TODO add your handling code here:
        ChartEnterpriseJPanel chartPanel = new ChartEnterpriseJPanel(userProcessContainer, business, user);
        userProcessContainer.add("View chart", chartPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnChartEntActionPerformed

    private void btnMngPharmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngPharmaActionPerformed
        // TODO add your handling code here:
        UpdateDeletePharmacy mngPharma = new UpdateDeletePharmacy(userProcessContainer, business, user);
        userProcessContainer.add("Manage Pharmacy", mngPharma);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngPharmaActionPerformed

    private void btnMngSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngSupActionPerformed
        // TODO add your handling code here:
        UpdateDeleteSupplier mngSup = new UpdateDeleteSupplier(userProcessContainer, business, user);
        userProcessContainer.add("Manage Supplier", mngSup);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngSupActionPerformed

    private void btnMngEmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngEmerActionPerformed
        // TODO add your handling code here:
        UpdateDeleteEmergencyUnit addHospital = new UpdateDeleteEmergencyUnit(userProcessContainer, business, user);
        userProcessContainer.add("Create Hospital", addHospital);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngEmerActionPerformed

    private void btnMngInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngInsuranceActionPerformed
        // TODO add your handling code here:
        UpdateDeleteInsuranceCompany mngIns = new UpdateDeleteInsuranceCompany(userProcessContainer, business, user);
        userProcessContainer.add("Manage Insurance", mngIns);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngInsuranceActionPerformed

    private void btnAddSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupActionPerformed
        // TODO add your handling code here:
        AddSupplierJPanel addSupplier = new AddSupplierJPanel(userProcessContainer, business);
        userProcessContainer.add("Add Supplier", addSupplier);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddSupActionPerformed

    private void btnAddEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmergencyActionPerformed
        // TODO add your handling code here:
        AddEmergencyUnitJPanel addEmergency = new AddEmergencyUnitJPanel(userProcessContainer, business);
        userProcessContainer.add("Add Emergency", addEmergency);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddEmergencyActionPerformed

    private void btnAddInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInsActionPerformed
        // TODO add your handling code here:
        AddInsuranceCompanyJPanel addIns = new AddInsuranceCompanyJPanel(userProcessContainer, business);
        userProcessContainer.add("Add Insurance", addIns);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddInsActionPerformed

    private void btnAddPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPharmacyActionPerformed
        // TODO add your handling code here:
        AddPharmacy addPharmacy = new AddPharmacy(userProcessContainer, business);
        userProcessContainer.add("Add Pharmacy", addPharmacy);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddPharmacyActionPerformed

    private void btnMngLabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngLabsActionPerformed
        // TODO add your handling code here:

        UpdateDeleteLab mngLab = new UpdateDeleteLab(userProcessContainer, business, user);
        userProcessContainer.add("Manage Lab", mngLab);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngLabsActionPerformed

    private void btnAddLabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLabsActionPerformed
        // TODO add your handling code here:
        AddLabJPanel AddLabs = new AddLabJPanel(userProcessContainer, business);
        userProcessContainer.add("Add Lab", AddLabs);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddLabsActionPerformed

    private void btnAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalActionPerformed
        AddHospital addHospital = new AddHospital(userProcessContainer, business);
        userProcessContainer.add("Add Hospital", addHospital);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddHospitalActionPerformed

    private void btnAddHospital1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospital1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddHospital1ActionPerformed

    private void btnAddLabs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLabs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddLabs1ActionPerformed

//
//    public void populateData() {
//         
//        DefaultPieDataset dataSet = new DefaultPieDataset();
//        int Hospital = 0;
//        int Pharmacy = 0;
//        int Lab = 0;
//        int Delivery = 0;
//        int Insurance = 0;
//        int Emergency = 0;
//        int Supplier = 0;
//        
//        
//        try {
//
//            for(Network network:business.getNetworkList()){
//            System.out.println("nett"+network);
//            for(Enterprise org : network.getEnterpriseDirectory().getEnterpriseList()){
//                   System.out.println("nett"+network.getEnterpriseDirectory().getEnterpriseList());
//               
//
//                if (org.getEnterpriseType().getValue().equals("Hospital")) {
//                          System.out.println("nett111"+org);
//                    Hospital++;
//                } else if (org.getEnterpriseType().getValue().equals("Pharmacy")) {
//                    Pharmacy++;
//                } else if (org.getEnterpriseType().getValue().equals("Lab")) {
//                  Lab++;
//                } else if (org.getEnterpriseType().getValue().equals("Delivery")) {
//                    Delivery++;
//                } else if (org.getEnterpriseType().getValue().equals("Insurance")) {
//                   Insurance++;
//                } else if (org.getEnterpriseType().getValue().equals("Emergency")){
//                    Emergency++;
//                } else if (org.getEnterpriseType().getValue().equals("Supplier")) {
//                     Supplier++;
//                } 
//                }
//            
//        }
//            System.out.println("asss"+Hospital);
//            dataSet.setValue("Hospitals", Hospital);
//            dataSet.setValue("Pharmacy", Pharmacy);
//            dataSet.setValue("Lab", Lab);
//            dataSet.setValue("Delivery", Delivery);
//            dataSet.setValue("Insurance", Insurance);
//            dataSet.setValue("Emergency", Emergency);
//            dataSet.setValue("Supplier", Supplier);
//
//            JFreeChart chart = ChartFactory.createPieChart3D("Enterprises", dataSet, true, true, Locale.ENGLISH);
//            chart.setBackgroundPaint(Color.WHITE);
//            chart.getTitle().setPaint(Color.DARK_GRAY);
//            ChartPanel chartpanel = new ChartPanel(chart);
//            chartpanel.setDomainZoomable(true);
//
//            jPanel4.setLayout(new BorderLayout());
//            jPanel4.add(chartpanel, BorderLayout.EAST);
//            jPanel4.setVisible(true);
//        } catch (NullPointerException npe) {
//            JOptionPane.showMessageDialog(null, " No Data to display");
//            return;
//        }
//
//    }
//      public void populateData1() {
//         
//        
//        DefaultPieDataset dataSet = new DefaultPieDataset();
//        int Doctor = 0;
//        int Patient = 0;
//        int DeliveryMan = 0;
//        int InsuranceAdmin = 0;
//        int PharamacyAdmin = 0;
//        int LabAdmin = 0;
//        int SupplierAdmin = 0;
//        int EmergencyAdmin=0;
//        
//        
//        try {
//         
//       for(Network network:business.getNetworkList()){
//            System.out.println("nett"+network);
//            for(Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
//                   System.out.println("nett"+network.getEnterpriseDirectory().getEnterpriseList());
//               
//                   for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
//                if (org.getEnterpriseType1().getValue().equals("Doctor")) {
//                   Doctor++;
//                } else if (org.getEnterpriseType1().getValue().equals("Patient")) {
//                    Patient++;
//                } else if (org.getEnterpriseType1().getValue().equals("DeliveryMan")) {
//                 DeliveryMan++;
//                } else if (org.getEnterpriseType1().getValue().equals("InsuranceAdmin")) {
//                   InsuranceAdmin++;
//                } else if (org.getEnterpriseType1().getValue().equals("PharamacyAdmin")) {
//                   PharamacyAdmin++;
//                } else if (org.getEnterpriseType1().getValue().equals("LabAdmin")){
//                    LabAdmin++;
//                } else if (org.getEnterpriseType1().getValue().equals("SupplierAdmin")) {
//                   SupplierAdmin++;
//                } else if (org.getEnterpriseType1().getValue().equals("EmergencyAdmin")) {
//                 EmergencyAdmin++;
//                }
//                
//            
//        }
//       
//            }
//       
//       }
//
//            dataSet.setValue("Doctor Organization", Doctor);
//            dataSet.setValue("Patient Organization", Patient);
//            dataSet.setValue("Delivery Organization", DeliveryMan);
//            dataSet.setValue("Insurance Organization", InsuranceAdmin);
//            dataSet.setValue("Pharamacy Organization", PharamacyAdmin);
//            dataSet.setValue("Lab Organization", LabAdmin);
//            dataSet.setValue("Emergency Organization", EmergencyAdmin);
//            dataSet.setValue("Supplier Organization", SupplierAdmin);
//
//            JFreeChart chart = ChartFactory.createPieChart3D("Organizations", dataSet, true, true, Locale.ENGLISH);
//            chart.setBackgroundPaint(Color.WHITE);
//            chart.getTitle().setPaint(Color.DARK_GRAY);
//            ChartPanel chartpanel = new ChartPanel(chart);
//            chartpanel.setDomainZoomable(true);
//
//            jPanel3.setLayout(new BorderLayout());
//            jPanel3.add(chartpanel, BorderLayout.EAST);
//            jPanel3.setVisible(true);
//        } catch (NullPointerException npe) {
//            JOptionPane.showMessageDialog(null, " No Data to display");
//            return;
//        }
//
//    }
//    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmergency;
    private javax.swing.JButton btnAddHospital;
    private javax.swing.JButton btnAddHospital1;
    private javax.swing.JButton btnAddIns;
    private javax.swing.JButton btnAddLabs;
    private javax.swing.JButton btnAddLabs1;
    private javax.swing.JButton btnAddPharmacy;
    private javax.swing.JButton btnAddSup;
    private javax.swing.JButton btnChartEnt;
    private javax.swing.JButton btnMngEmer;
    private javax.swing.JButton btnMngInsurance;
    private javax.swing.JButton btnMngLabs;
    private javax.swing.JButton btnMngPharma;
    private javax.swing.JButton btnMngSup;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
