/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Administrator;

import Business.EcoSystem;
import Business.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Smithi
 */
public class UpdateDeleteSupplier extends javax.swing.JPanel {

    /**
     * Creates new form UpdateDeleteSupplier
     */
    JPanel userProcessContainer;
    EcoSystem business;
    UserAccount user;
    
    public UpdateDeleteSupplier(JPanel userProcessContainer, EcoSystem business, UserAccount user) {
//        initComponents();
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.user = user;
        populateTable();
//         if(system.getNetworkList().size()>0 ){
//            populateTable();
//        }else{
//             JOptionPane.showMessageDialog(null, "No Supplier added");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnDelSup = new javax.swing.JButton();
        btnUpdSup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        supTable = new javax.swing.JTable();
        btnBackSup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addrTxtFieldSup = new javax.swing.JTextField();
        nameTxtFieldSup = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboSupLocation = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(52, 7, 116));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 7, 116));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Username:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 90, 30));

        btnDelSup.setBackground(new java.awt.Color(52, 7, 116));
        btnDelSup.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDelSup.setForeground(new java.awt.Color(255, 255, 255));
        btnDelSup.setText("DELETE");
        btnDelSup.setPreferredSize(new java.awt.Dimension(156, 43));
        btnDelSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelSupActionPerformed(evt);
            }
        });
        add(btnDelSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 110, 30));

        btnUpdSup.setBackground(new java.awt.Color(52, 7, 116));
        btnUpdSup.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdSup.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdSup.setText("UPDATE");
        btnUpdSup.setPreferredSize(new java.awt.Dimension(156, 43));
        btnUpdSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdSupActionPerformed(evt);
            }
        });
        add(btnUpdSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 110, 30));

        supTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "UserName"
            }
        ));
        supTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        supTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 110));

        btnBackSup.setBackground(new java.awt.Color(52, 7, 116));
        btnBackSup.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBackSup.setForeground(new java.awt.Color(255, 255, 255));
        btnBackSup.setText("<<");
        btnBackSup.setPreferredSize(new java.awt.Dimension(80, 30));
        btnBackSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSupActionPerformed(evt);
            }
        });
        add(btnBackSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel5.setBackground(new java.awt.Color(52, 7, 116));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-supplier-64.png"))); // NOI18N
        jLabel5.setText("SUPPLIER  DETAILS");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 510, 70));

        jLabel6.setBackground(new java.awt.Color(52, 7, 116));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 7, 116));
        jLabel6.setText("Location");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 70, 20));

        addrTxtFieldSup.setPreferredSize(new java.awt.Dimension(164, 30));
        add(addrTxtFieldSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 150, 20));

        nameTxtFieldSup.setPreferredSize(new java.awt.Dimension(164, 30));
        add(nameTxtFieldSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 150, 20));

        jLabel2.setBackground(new java.awt.Color(52, 7, 116));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 70, 30));

        comboSupLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show All", "Brigham", "Cambridge", "Brookline", "Longwood", "Fenway" }));
        comboSupLocation.setPreferredSize(new java.awt.Dimension(140, 30));
        comboSupLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSupLocationActionPerformed(evt);
            }
        });
        add(comboSupLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 170, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supplier123.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 420, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelSupActionPerformed
        // TODO add your handling code here:

        Object selectedItem = comboSupLocation.getSelectedItem();
        String location = selectedItem.toString();
        int selectedRow = supTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");

        } else {
            Enterprise lab = (Enterprise) supTable.getValueAt(selectedRow, 0);
            business.getEnterpriseDirectory().getEnterpriseList().remove(lab);
            UserAccount ua = business.getUserAccountDirectory().findUserAccount(lab.getName());
            business.getUserAccountDirectory().getUserAccountList().remove(ua);

            //            LabDirectory ld = system.getLabDirectory();
            //            ld.deleteLab(l);
            JOptionPane.showMessageDialog(null, "Supplier " + nameTxtFieldSup.getText() + " deleted");
            populateTable();
            nameTxtFieldSup.setText("");
            addrTxtFieldSup.setText("");

        }
    }//GEN-LAST:event_btnDelSupActionPerformed

    private void btnUpdSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdSupActionPerformed
        // TODO add your handling code here:

        int selectedRow = supTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        } else {
            //            updateJPanel.setVisible(true);
            //            System.out.println("I am here");
            Object selectedItem = comboSupLocation.getSelectedItem();
            String loc = selectedItem.toString();
            //    for(Enterprise lab: system.findNetwork(city).getEnterpriseDirectory().getEnterpriseList()){
                //        if lab.getName().equals(selectedItem)
                //    }
            Enterprise lab = (Enterprise) supTable.getValueAt(selectedRow, 0);
            UserAccount ua = business.getUserAccountDirectory().findUserAccount(lab.getName());
            if (!nameTxtFieldSup.getText().matches("[a-zA-Z_]+")) {
                JOptionPane.showMessageDialog(this, "Enter proper name! Name should be string!");
                nameTxtFieldSup.setText("");
                return;
            }
            else if (strongUsername() == false) {

                addrTxtFieldSup.setText("");
                JOptionPane.showMessageDialog(null, "Username should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
                return;
            }
            else {
            }
            lab.setName(nameTxtFieldSup.getText());
            ua.getEmployee().setName(nameTxtFieldSup.getText());
            ua.setUsername(addrTxtFieldSup.getText());
            populateTable();
            nameTxtFieldSup.setText("");
            addrTxtFieldSup.setText("");
        }
    }//GEN-LAST:event_btnUpdSupActionPerformed

    private void supTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supTableMouseClicked
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) supTable.getModel();

        String name = dtm.getValueAt(supTable.getSelectedRow(), 0).toString();
        String address = dtm.getValueAt(supTable.getSelectedRow(), 1).toString();
        nameTxtFieldSup.setText(name);
        addrTxtFieldSup.setText(address);
    }//GEN-LAST:event_supTableMouseClicked

    private void btnBackSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSupActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_btnBackSupActionPerformed

    private void comboSupLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSupLocationActionPerformed
        // TODO add your handling code here:
        Object selectedItem = comboSupLocation.getSelectedItem();
        String loc = selectedItem.toString();
        if(loc.equals("Show All")){
            populateTable();
        }else{
            populateTableByLoc();
        }
    }//GEN-LAST:event_comboSupLocationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrTxtFieldSup;
    private javax.swing.JButton btnBackSup;
    private javax.swing.JButton btnDelSup;
    private javax.swing.JButton btnUpdSup;
    private javax.swing.JComboBox<String> comboSupLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxtFieldSup;
    private javax.swing.JTable supTable;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
            Object selectedItem = comboSupLocation.getSelectedItem();
        String loc = selectedItem.toString();
        DefaultTableModel model = (DefaultTableModel) supTable.getModel();
        model.setRowCount(0);
//        System.out.println("Ap was here " +city);
//        System.out.println("ap here " +system.findNetwork(city).getEnterpriseDirectory().getEnterpriseList());

        for(Enterprise supplier: business.getEnterpriseDirectory().getEnterpriseList()){
                     System.out.println(supplier.getEnterpriseType().getValue().equals("Supplier"));
                     System.out.println(supplier.getUserAccountDirectory().getUserAccountList());
                     System.out.println(supplier.getName());
                     System.out.println(supplier.getUserAccountDirectory().findUserAccount(supplier.getName()));
                if(supplier.getEnterpriseType().getValue().equals("Supplier")){
            Object[] row = new Object[2];
            row[0] = supplier;
//            System.out.println("LISTING IT" +system.getUserAccountDirectory().getUserAccountList());
//            System.out.println(lab.getName());
                     for(UserAccount ua : business.getUserAccountDirectory().getUserAccountList()){
                         System.out.println(ua.getEmployee().getName());
         }
            UserAccount ua = business.getUserAccountDirectory().findUserAccount(supplier.getName());
            
            row[1] = ua.getUsername();
            model.addRow(row);
 
        }
        }
    }

    private void populateTableByLoc() {
        Object selectedItem = comboSupLocation.getSelectedItem();
        String loc = selectedItem.toString();
        DefaultTableModel model = (DefaultTableModel) supTable.getModel();
        model.setRowCount(0);

        for (Enterprise sup : business.getEnterpriseDirectory().getEnterpriseList()) {
            if (sup.getEnterpriseType().getValue().equals("Supplier") && business.getUserAccountDirectory().findUserAccount(sup.getName()).getEmployee().getLocation().equals(loc)) {
                Object[] row = new Object[2];
                row[0] = sup;

                UserAccount ua = business.getUserAccountDirectory().findUserAccount(sup.getName());
                row[1] = ua.getUsername();
                model.addRow(row);
            }
        }
    }

    private boolean strongUsername() {
        Pattern pat = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m = pat.matcher(addrTxtFieldSup.getText());
        boolean boo = m.matches();
        return boo;
    }

    
}
