/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmergencyAdmin;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Soumya
 */
public class CompleteEmergencyRequest extends javax.swing.JPanel {

    /**
     * Creates new form CompleteEmergencyRequestJPanel
     */
    JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem business;
    
    
    public CompleteEmergencyRequest(JPanel userProcessContainer, UserAccount ua, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua=ua;
        this.business=business;
        for (WorkRequest request : business.getWorkQueue().getWorkRequestList()) {

            if (request.getReceiver().equals(this.ua)) {
                txtPatientNameEmeReq.setText(request.getSender().getEmployee().getName());
                txtPatientStatusEmeReq.setText(request.getStatus());
//                pPhoneTxtField.setText(emergencyWorkRequest.getP().getPhoneNumber());
//                pAddrTxtField.setText(emergencyWorkRequest.getP().getAddress());
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientNameEmeReq = new javax.swing.JTextField();
        txtPatientStatusEmeReq = new javax.swing.JTextField();
        btnEmereqMC = new javax.swing.JButton();
        btnEmereqMI = new javax.swing.JButton();
        btnBackEmeReq = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 7, 116));
        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 7, 116));
        jLabel5.setText("Patient Status:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, 30));
        add(txtPatientNameEmeReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 190, 30));
        add(txtPatientStatusEmeReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 190, 30));

        btnEmereqMC.setBackground(new java.awt.Color(52, 7, 116));
        btnEmereqMC.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEmereqMC.setForeground(new java.awt.Color(255, 255, 255));
        btnEmereqMC.setText("MARK AS COMPLETE");
        btnEmereqMC.setPreferredSize(new java.awt.Dimension(156, 43));
        btnEmereqMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmereqMCActionPerformed(evt);
            }
        });
        add(btnEmereqMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 200, 40));

        btnEmereqMI.setBackground(new java.awt.Color(52, 7, 116));
        btnEmereqMI.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEmereqMI.setForeground(new java.awt.Color(255, 255, 255));
        btnEmereqMI.setText("MARK AS INCOMPLETE");
        btnEmereqMI.setPreferredSize(new java.awt.Dimension(156, 43));
        btnEmereqMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmereqMIActionPerformed(evt);
            }
        });
        add(btnEmereqMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 200, 40));

        btnBackEmeReq.setBackground(new java.awt.Color(52, 7, 116));
        btnBackEmeReq.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBackEmeReq.setForeground(new java.awt.Color(255, 255, 255));
        btnBackEmeReq.setText("<<");
        btnBackEmeReq.setPreferredSize(new java.awt.Dimension(80, 30));
        btnBackEmeReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackEmeReqActionPerformed(evt);
            }
        });
        add(btnBackEmeReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        enterpriseLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(52, 7, 116));
        enterpriseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-ambulance-40.png"))); // NOI18N
        enterpriseLabel.setText("COMPLETE EMERGENCY REQUEST");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 400, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emergencyImg.jpg"))); // NOI18N
        jLabel7.setFocusable(false);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 440, 390));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmereqMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmereqMCActionPerformed
        // TODO add your handling code here:
                for (WorkRequest request : business.getWorkQueue().getWorkRequestList()) {

            if (request.getReceiver().equals(this.ua)) {
                request.setStatus("Help completed");
            }
                }
             JOptionPane.showMessageDialog(this, "Help completed");
    }//GEN-LAST:event_btnEmereqMCActionPerformed

    private void btnEmereqMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmereqMIActionPerformed
        // TODO add your handling code here:
                        
        for (WorkRequest request : business.getWorkQueue().getWorkRequestList()) {

            if (request.getReceiver().equals(this.ua)) {
                request.setStatus("Help awaited!");
            }
                }
                JOptionPane.showMessageDialog(this, "Help Awaited.");
    }//GEN-LAST:event_btnEmereqMIActionPerformed

    private void btnBackEmeReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackEmeReqActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackEmeReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackEmeReq;
    private javax.swing.JButton btnEmereqMC;
    private javax.swing.JButton btnEmereqMI;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtPatientNameEmeReq;
    private javax.swing.JTextField txtPatientStatusEmeReq;
    // End of variables declaration//GEN-END:variables
}
